# Importing Important Libraries For Extraction and Transformation of Data

In [1]:
import pandas as pd
import numpy as np
import fastf1
import os

## Caching Data from Fast F1

In [2]:
fastf1.Cache.enable_cache("f1_cache")

### Loading Data of 2023,2024,2025 Austrain Grand Prix

In [3]:
os.makedirs("f1_cache", exist_ok=True)
fastf1.Cache.enable_cache("f1_cache")

sessions = {}

for year in range(2023, 2026):
    try:
        session = fastf1.get_session(year, 'Australia', 'R')
        session.load()
        sessions[year] = session
        print(f"{year} loaded successfully")
    except Exception as e:
        print(f"Failed for {year}: {e}")

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']

2023 loaded successfully

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']

2024 loaded successfully

core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver 241: Position data is incomplete!
_api        WARNING 	Driver 242: Position data is incomplete!
_api        WARNING 	Driver 243: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

2025 loaded successfully

## Fecthing important Columns

In [4]:
laps={}
for year in range(2023, 2026):
    
    laps[year] = sessions[year].laps[["Driver","LapTime","Sector1Time","Sector2Time","Sector3Time"]].copy()

In [5]:
laps[2023].head()

,Driver,LapTime,Sector1Time,Sector2Time,Sector3Time
0,VER,0 days 00:01:41.571000,NaT,0 days 00:00:18.707000,0 days 00:00:46.357000
1,VER,0 days 00:02:12.105000,0 days 00:00:48.846000,0 days 00:00:31.614000,0 days 00:00:51.645000
2,VER,0 days 00:02:10.657000,0 days 00:00:46.836000,0 days 00:00:29.178000,0 days 00:00:54.643000
3,VER,0 days 00:01:23.391000,0 days 00:00:28.900000,0 days 00:00:18.326000,0 days 00:00:36.165000
4,VER,0 days 00:01:23.104000,0 days 00:00:28.935000,0 days 00:00:18.347000,0 days 00:00:35.822000

## Dropping all the Null Values

In [6]:
for year in range (2023,2026):
    laps[year].dropna(inplace=True)

## Converting the Times in Seconds

In [7]:
for year in range (2023,2026):
    for col in["LapTime", "Sector1Time", "Sector2Time", "Sector3Time"]:
        laps[year][f"{col} (s)"] = laps[year][col].dt.total_seconds()

## Taking Average of all the Times

In [8]:
sector_times = {}

for year in range(2023,2026):
    sector_times[year] = laps[year].groupby("Driver").agg({
        "Sector1Time (s)":"mean",
        "Sector2Time (s)":"mean",
        "Sector3Time (s)":"mean"
    }).reset_index()

## Add New Columns Like Total Sector Time and Year

In [9]:
for year in range(2023, 2026):
    sector_times[year][f"TotalSectorTime_{year} (s)"]=(
        sector_times[year]["Sector1Time (s)"]+
        sector_times[year]["Sector2Time (s)"]+
        sector_times[year]["Sector3Time (s)"]
    )
    sector_times[year]["Year"] = year

In [10]:
sector_times[2024]

,Driver,Sector1Time (s),Sector2Time (s),Sector3Time (s),TotalSectorTime_2024 (s),Year
0,ALB,29.373893,18.522982,36.676339,84.573214,2024
1,ALO,29.153140,18.555982,36.735298,84.444421,2024
2,BOT,29.563875,18.826607,36.866768,85.257250,2024
3,GAS,29.606286,18.629214,36.862571,85.098071,2024
4,HAM,29.553357,18.145857,36.924929,84.624143,2024
5,HUL,29.372895,18.810175,36.632298,84.815368,2024
6,LEC,28.882860,18.224632,36.027404,83.134895,2024
7,MAG,29.324036,18.430304,36.807393,84.561732,2024
8,NOR,28.914263,18.278035,36.017579,83.209877,2024
9,OCO,29.603321,18.689143,37.145732,85.438196,2024
10,PER,29.184842,18.490947,36.372000,84.047789,2024
11,PIA,29.249702,18.264842,36.197333,83.711877,2024
12,RIC,29.443357,18.610071,36.602036,84.655464,2024
13,RUS,28.849891,18.260964,36.395036,83.505891,2024
14,SAI,28.811263,18.430614,35.889140,83.131018,2024
15,STR,29.152000,18.742211,36.794035,84.688246,2024
16,TSU,29.237351,18.873316,36.611070,84.721737,2024
17,VER,29.208000,18.474000,35.925000,83.607000,2024
18,ZHO,29.455304,18.804321,36.962607,85.222232,2024

## Concating all the tables

In [11]:
combined_sector_time = pd.concat(sector_times.values(), ignore_index=True)

In [12]:
combined_sector_time

,Driver,Sector1Time (s),Sector2Time (s),Sector3Time (s),TotalSectorTime_2023 (s),Year,TotalSectorTime_2024 (s),TotalSectorTime_2025 (s)
0,ALB,36.661600,22.926600,42.705400,102.293600,2023,NaN,NaN
1,ALO,29.568863,19.144961,36.672275,85.386098,2023,NaN,NaN
2,BOT,30.264860,19.164900,37.449260,86.879020,2023,NaN,NaN
3,DEV,30.642140,19.425180,37.693360,87.760680,2023,NaN,NaN
4,GAS,29.669765,18.958725,36.978529,85.607020,2023,NaN,NaN
5,HAM,30.528673,19.423365,37.291846,87.243885,2023,NaN,NaN
6,HUL,29.815098,19.174549,37.051902,86.041549,2023,NaN,NaN
7,MAG,30.205939,19.053918,37.344633,86.604490,2023,NaN,NaN
8,NOR,29.770627,19.360314,36.842412,85.973353,2023,NaN,NaN
9,OCO,30.065784,19.163157,36.823059,86.052000,2023,NaN,NaN
10,PER,29.666353,18.895510,36.922098,85.483961,2023,NaN,NaN
11,PIA,30.157549,19.420471,37.080980,86.659000,2023,NaN,NaN
12,RUS,31.926571,20.343571,41.037571,93.307714,2023,NaN,NaN
13,SAI,29.631784,19.036118,37.077431,85.745333,2023,NaN,NaN
14,SAR,30.287960,19.152100,37.911020,87.351080,2023,NaN,NaN
15,STR,29.734431,19.124490,36.832333,85.691255,2023,NaN,NaN
16,TSU,30.426647,19.350451,37.511882,87.288980,2023,NaN,NaN
17,VER,29.509294,19.072392,36.571980,85.153667,2023,NaN,NaN
18,ZHO,30.484333,19.124843,37.415137,87.024314,2023,NaN,NaN
19,ALB,29.373893,18.522982,36.676339,NaN,2024,84.573214,NaN
20,ALO,29.153140,18.555982,36.735298,NaN,2024,84.444421,NaN
21,BOT,29.563875,18.826607,36.866768,NaN,2024,85.257250,NaN
22,GAS,29.606286,18.629214,36.862571,NaN,2024,85.098071,NaN
23,HAM,29.553357,18.145857,36.924929,NaN,2024,84.624143,NaN
24,HUL,29.372895,18.810175,36.632298,NaN,2024,84.815368,NaN
25,LEC,28.882860,18.224632,36.027404,NaN,2024,83.134895,NaN
26,MAG,29.324036,18.430304,36.807393,NaN,2024,84.561732,NaN
27,NOR,28.914263,18.278035,36.017579,NaN,2024,83.209877,NaN
28,OCO,29.603321,18.689143,37.145732,NaN,2024,85.438196,NaN
29,PER,29.184842,18.490947,36.372000,NaN,2024,84.047789,NaN
30,PIA,29.249702,18.264842,36.197333,NaN,2024,83.711877,NaN
31,RIC,29.443357,18.610071,36.602036,NaN,2024,84.655464,NaN
32,RUS,28.849891,18.260964,36.395036,NaN,2024,83.505891,NaN
33,SAI,28.811263,18.430614,35.889140,NaN,2024,83.131018,NaN
34,STR,29.152000,18.742211,36.794035,NaN,2024,84.688246,NaN
35,TSU,29.237351,18.873316,36.611070,NaN,2024,84.721737,NaN
36,VER,29.208000,18.474000,35.925000,NaN,2024,83.607000,NaN
37,ZHO,29.455304,18.804321,36.962607,NaN,2024,85.222232,NaN
38,ALB,35.719019,23.072491,45.361585,NaN,2025,NaN,104.153094
39,ALO,34.163393,20.654786,42.318464,NaN,2025,NaN,97.136643
40,ANT,35.494604,22.989604,45.382472,NaN,2025,NaN,103.866679
41,BEA,35.698846,22.422365,44.873038,NaN,2025,NaN,102.994250
42,BOR,35.187725,22.107975,44.324750,NaN,2025,NaN,101.620450
43,GAS,35.688340,22.937509,45.711566,NaN,2025,NaN,104.337415
44,HAM,35.578327,22.742058,45.090731,NaN,2025,NaN,103.411115
45,HUL,35.636981,22.843642,45.571226,NaN,2025,NaN,104.051849
46,LAW,34.684293,22.170073,43.750780,NaN,2025,NaN,100.605146
47,LEC,35.325635,22.557423,45.578423,NaN,2025,NaN,103.461481
48,NOR,35.904404,22.791442,44.469558,NaN,2025,NaN,103.165404
49,OCO,36.053885,22.091019,44.897635,NaN,2025,NaN,103.042538
50,PIA,35.322980,22.366235,44.028137,NaN,2025,NaN,101.717353
51,RUS,35.941231,22.722885,44.619192,NaN,2025,NaN,103.283308
52,STR,35.525094,22.990245,45.559038,NaN,2025,NaN,104.074377
53,TSU,35.572904,22.739712,45.262135,NaN,2025,NaN,103.574750
54,VER,35.516923,22.584731,44.930827,NaN,2025,NaN,103.032481

## Clean Air Race Pace (Best Time From Practice Session Before Qualifying Round.)

In [13]:
clean_air_race_pace = {
    #McLaren
    "NOR":00,               #Lando Norris 🇬🇧
    "PIA":00,               #Oscar Piastri 🇦🇺
    #Red Bull Racing
    "VER":00,               #Max Verstappen 🇳🇱
    "HAD":00,               #Isack Hadjar 🇫🇷
    #Ferrari
    "LEC":00,               #Charles Leclerc 🇲🇨
    "HAM":00,               #Lewis Hamilton 🇬🇧
    #Mercedes
    "RUS":00,               #Geaorge Russell 🇬🇧
    "ANT":00,               #Andrea Kimi Antonelli 🇮🇹
    #Aston Martin Aramco
    "ALO":00,               #Fernando Alonso 🇪🇸
    "STR":00,               #Lance Stroll 🇨🇦
    #Williams
    "ALB":00,               #Alexander Albon 🇹🇭
    "SAI":00,               #Carlos Sainz Jr. 🇪🇸
    #Haas
    "OCO":00,               #Esteban Ocon 🇫🇷
    "BEA":00,               #Oliver Bearman 🇬🇧
    #Alpine
    "GAS":00,               #Piette Gasly 🇫🇷
    "COL":00,               #Franco Colapinto 🇦🇷
    #Audi
    "HUL":00,               #Nico Hulkenberg 🇩🇪
    "BOR":00,               #Gabriel Bortoleto 🇧🇷
    #Cadillac
    "PER":00,               #Sergio Perez 🇲🇽
    "BOT":00,               #Valtteri Bottas 🇫🇮
    #Racing Bulls
    "LAW":00,               #Liam Lawson 🇳🇿
    "LIN":00                #Arvid Lindblad 🇬🇧
}

## List of the Current Drivers

In [14]:
Driver = [
    #McLaren
    "NOR",               #Lando Norris 🇬🇧
    "PIA",               #Oscar Piastri 🇦🇺
    #Red Bull Racing
    "VER",               #Max Verstappen 🇳🇱
    "HAD",               #Isack Hadjar 🇫🇷
    #Ferrari
    "LEC",               #Charles Leclerc 🇲🇨
    "HAM",               #Lewis Hamilton 🇬🇧
    #Mercedes
    "RUS",               #Geaorge Russell 🇬🇧
    "ANT",               #Andrea Kimi Antonelli 🇮🇹
    #Aston Martin Aramco
    "ALO",               #Fernando Alonso 🇪🇸
    "STR",               #Lance Stroll 🇨🇦
    #Williams
    "ALB",               #Alexander Albon 🇹🇭
    "SAI",               #Carlos Sainz Jr. 🇪🇸
    #Haas
    "OCO",               #Esteban Ocon 🇫🇷
    "BEA",               #Oliver Bearman 🇬🇧
    #Alpine
    "GAS",               #Piette Gasly 🇫🇷
    "COL",               #Franco Colapinto 🇦🇷
    #Audi
    "HUL",               #Nico Hulkenberg 🇩🇪
    "BOR",               #Gabriel Bortoleto 🇧🇷
    #Cadillac
    "PER",               #Sergio Perez 🇲🇽
    "BOT",               #Valtteri Bottas 🇫🇮
    #Racing Bulls
    "LAW",               #Liam Lawson 🇳🇿
    "LIN"                #Arvid Lindblad 🇬🇧

]

## Qualifying Time

In [15]:
qualifying_2026 = pd.DataFrame({
    "Driver":Driver,
    "QualifyingTime (s)":[
        #McLaren
        00,                 #NOR
        00,                 #PIA
        #Red Bull Racing
        00,                 #VER
        00,                 #HAD
        #Ferrari
        00,                 #LEC
        00,                 #HAM
        #Mercedes
        00,                 #RUS
        00,                 #ANT
        #Aston Martin Aramco
        00,                 #ALO
        00,                 #STR
        #Williams
        00,                 #ALB
        00,                 #SAI
        #Haas
        00,                 #OCO
        00,                 #BEA
        #Alpine
        00,                 #GAS
        00,                 #COL
        #Audi
        00,                 #HUL
        00,                 #BOR
        #Cadillac
        00,                 #PER
        00,                 #BOT
        #Racing Bulls
        00,                 #LAW
        00                  #LIN
    ]
})

## Combining Qualifying Time and Clean Air Race Pace

In [16]:
qualifying_2026["CleanAirRacePace (s)"] = qualifying_2026["Driver"].map(clean_air_race_pace)

In [17]:
qualifying_2026

   Driver  QualifyingTime (s)  CleanAirRacePace (s)
0     NOR                   0                     0
1     PIA                   0                     0
2     VER                   0                     0
3     HAD                   0                     0
4     LEC                   0                     0
5     HAM                   0                     0
6     RUS                   0                     0
7     ANT                   0                     0
8     ALO                   0                     0
9     STR                   0                     0
10    ALB                   0                     0
11    SAI                   0                     0
12    OCO                   0                     0
13    BEA                   0                     0
14    GAS                   0                     0
15    COL                   0                     0
16    HUL                   0                     0
17    BOR                   0                     0
18    PER                   0                     0
19    BOT                   0                     0
20    LAW                   0                     0
21    LIN                   0                     0

## Team Points(Currently Zero Due to Start of Season)

In [18]:
team_points = {
    "McLaren":00,
    "Mercedes":00,
    "Red Bull":00,
    "Williams":00,
    "Ferrari":00,
    "Haas":00,
    "Aston Martin":00,
    "Racing Bulls":00,
    "Alpine":00,
    "Audi":00,
    "Cardillac":00
}

## Scaling the Team Points (For Future Use)

In [19]:
from sklearn.preprocessing import MinMaxScaler

teams = list(team_points.keys())
points = np.array(list(team_points.values())).reshape(-1,1)

scaler = MinMaxScaler()
scaled_points = scaler.fit_transform(points)

team_performance_score = dict(zip(teams, scaled_points.flatten()))

## Mapping Drivers with their Respective Teams

In [20]:
driver_to_team = {
    "NOR":"McLaren",
    "PIA":"McLaren",

    "VER":"Red Bull",
    "HAD":"Red Bull",

    "LEC":"Ferrari",
    "HAM":"Ferrari",

    "RUS":"Mercedes",
    "ANT":"Mercedes",

    "ALO":"Aston Martin",
    "STR":"Aston Martin",

    "ALB":"Williams",
    "SAI":"Williams",

    "OCO":"Haas",
    "BEA":"Haas",

    "GAS":"Alpine",
    "COL":"Alpine",

    "HUL":"Audi",
    "BOR":"Audi",

    "PER":"Cardillac",
    "BOT":"Cardillac",
    
    "LAW":"Racing Bulls",
    "LIN":"Racing Bulls"  
}

## Combining Team and Team Performance data to Qualifying 2026 table

In [21]:
qualifying_2026["Team"] = qualifying_2026["Driver"].map(driver_to_team)
qualifying_2026["TeamPerformanceScore"] = qualifying_2026["Team"].map(team_performance_score)

In [22]:
qualifying_2026

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore
0,NOR,0,0,McLaren,0.0
1,PIA,0,0,McLaren,0.0
2,VER,0,0,Red Bull,0.0
3,HAD,0,0,Red Bull,0.0
4,LEC,0,0,Ferrari,0.0
5,HAM,0,0,Ferrari,0.0
6,RUS,0,0,Mercedes,0.0
7,ANT,0,0,Mercedes,0.0
8,ALO,0,0,Aston Martin,0.0
9,STR,0,0,Aston Martin,0.0
10,ALB,0,0,Williams,0.0
11,SAI,0,0,Williams,0.0
12,OCO,0,0,Haas,0.0
13,BEA,0,0,Haas,0.0
14,GAS,0,0,Alpine,0.0
15,COL,0,0,Alpine,0.0
16,HUL,0,0,Audi,0.0
17,BOR,0,0,Audi,0.0
18,PER,0,0,Cardillac,0.0
19,BOT,0,0,Cardillac,0.0
20,LAW,0,0,Racing Bulls,0.0
21,LIN,0,0,Racing Bulls,0.0

## Merging Data of qualifyingTime and Total Sector Time of 2023,2024,2025

In [23]:
merged_data = qualifying_2026.copy()

for year in range(2023, 2026):
    merged_data = merged_data.merge(
        sector_times[year][["Driver", f"TotalSectorTime_{year} (s)"]],
        on="Driver",
        how="left"
    )

In [24]:
merged_data

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s)
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481
3,HAD,0,0,Red Bull,0.0,NaN,NaN,NaN
4,LEC,0,0,Ferrari,0.0,NaN,83.134895,103.461481
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308
7,ANT,0,0,Mercedes,0.0,NaN,NaN,103.866679
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094
11,SAI,0,0,Williams,0.0,85.745333,83.131018,NaN
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538
13,BEA,0,0,Haas,0.0,NaN,NaN,102.994250
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415
15,COL,0,0,Alpine,0.0,NaN,NaN,NaN
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849
17,BOR,0,0,Audi,0.0,NaN,NaN,101.620450
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,NaN
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,NaN
20,LAW,0,0,Racing Bulls,0.0,NaN,NaN,100.605146
21,LIN,0,0,Racing Bulls,0.0,NaN,NaN,NaN

## Filling nan values of 2025 with the average values of 2023 and 2024

### This is done for the drivers whose data are present for 2023 and 2024 but where unable to perform in 2025 due to various reasons.

In [25]:
col_23 = "TotalSectorTime_2023 (s)"
col_24 = "TotalSectorTime_2024 (s)"
col_25 = "TotalSectorTime_2025 (s)"

mask = (
    merged_data[col_25].isna() &
    merged_data[col_23].notna() &
    merged_data[col_24].notna()
)

merged_data.loc[mask, col_25] = (
    merged_data.loc[mask, [col_23, col_24]].mean(axis=1)
)

In [26]:
merged_data

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s)
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481
3,HAD,0,0,Red Bull,0.0,NaN,NaN,NaN
4,LEC,0,0,Ferrari,0.0,NaN,83.134895,103.461481
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308
7,ANT,0,0,Mercedes,0.0,NaN,NaN,103.866679
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094
11,SAI,0,0,Williams,0.0,85.745333,83.131018,84.438175
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538
13,BEA,0,0,Haas,0.0,NaN,NaN,102.994250
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415
15,COL,0,0,Alpine,0.0,NaN,NaN,NaN
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849
17,BOR,0,0,Audi,0.0,NaN,NaN,101.620450
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,84.765875
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,86.068135
20,LAW,0,0,Racing Bulls,0.0,NaN,NaN,100.605146
21,LIN,0,0,Racing Bulls,0.0,NaN,NaN,NaN

## Adding a new column IsNewDriver to let the model know we have missing values and compute accordingly

In [27]:
merged_data["IsNewDriver"] = (
    merged_data["TotalSectorTime_2023 (s)"].isna() &
    merged_data["TotalSectorTime_2024 (s)"].isna()
).astype(int)

In [28]:
merged_data

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s),IsNewDriver
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404,0
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353,0
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481,0
3,HAD,0,0,Red Bull,0.0,NaN,NaN,NaN,1
4,LEC,0,0,Ferrari,0.0,NaN,83.134895,103.461481,0
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115,0
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308,0
7,ANT,0,0,Mercedes,0.0,NaN,NaN,103.866679,1
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643,0
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377,0
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094,0
11,SAI,0,0,Williams,0.0,85.745333,83.131018,84.438175,0
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538,0
13,BEA,0,0,Haas,0.0,NaN,NaN,102.994250,1
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415,0
15,COL,0,0,Alpine,0.0,NaN,NaN,NaN,1
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849,0
17,BOR,0,0,Audi,0.0,NaN,NaN,101.620450,1
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,84.765875,0
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,86.068135,0
20,LAW,0,0,Racing Bulls,0.0,NaN,NaN,100.605146,1
21,LIN,0,0,Racing Bulls,0.0,NaN,NaN,NaN,1

## Imputing all the NAN values With Global Median

In [29]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="median")

for year in range(2023, 2026):
    col = f"TotalSectorTime_{year} (s)"
    merged_data[[col]] = imputer.fit_transform(
        merged_data[[col]]
    )

In [30]:
merged_data

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s),IsNewDriver
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404,0
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353,0
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481,0
3,HAD,0,0,Red Bull,0.0,86.007451,84.444421,103.042538,1
4,LEC,0,0,Ferrari,0.0,86.007451,83.134895,103.461481,0
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115,0
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308,0
7,ANT,0,0,Mercedes,0.0,86.007451,84.444421,103.866679,1
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643,0
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377,0
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094,0
11,SAI,0,0,Williams,0.0,85.745333,83.131018,84.438175,0
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538,0
13,BEA,0,0,Haas,0.0,86.007451,84.444421,102.994250,1
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415,0
15,COL,0,0,Alpine,0.0,86.007451,84.444421,103.042538,1
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849,0
17,BOR,0,0,Audi,0.0,86.007451,84.444421,101.620450,1
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,84.765875,0
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,86.068135,0
20,LAW,0,0,Racing Bulls,0.0,86.007451,84.444421,100.605146,1
21,LIN,0,0,Racing Bulls,0.0,86.007451,84.444421,103.042538,1

In [31]:
merged_data.columns

Index(['Driver', 'QualifyingTime (s)', 'CleanAirRacePace (s)', 'Team',
       'TeamPerformanceScore', 'TotalSectorTime_2023 (s)',
       'TotalSectorTime_2024 (s)', 'TotalSectorTime_2025 (s)', 'IsNewDriver'],
      dtype='object')

# Lets try to predict 2025 using 2023 and 2024 data and make our model accurate

In [32]:
merged_data1 = merged_data.copy()

In [33]:
merged_data1

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s),IsNewDriver
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404,0
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353,0
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481,0
3,HAD,0,0,Red Bull,0.0,86.007451,84.444421,103.042538,1
4,LEC,0,0,Ferrari,0.0,86.007451,83.134895,103.461481,0
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115,0
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308,0
7,ANT,0,0,Mercedes,0.0,86.007451,84.444421,103.866679,1
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643,0
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377,0
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094,0
11,SAI,0,0,Williams,0.0,85.745333,83.131018,84.438175,0
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538,0
13,BEA,0,0,Haas,0.0,86.007451,84.444421,102.994250,1
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415,0
15,COL,0,0,Alpine,0.0,86.007451,84.444421,103.042538,1
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849,0
17,BOR,0,0,Audi,0.0,86.007451,84.444421,101.620450,1
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,84.765875,0
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,86.068135,0
20,LAW,0,0,Racing Bulls,0.0,86.007451,84.444421,100.605146,1
21,LIN,0,0,Racing Bulls,0.0,86.007451,84.444421,103.042538,1

In [35]:
qualifying_data_2025 = fastf1.get_session(2025,'Australia','Q')

In [36]:
qualifying_data_2025.load()

core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '4'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
_api        WARNING 	Driver  2: Car data is incomplete!
_api        WARNING 	Driver  3: Car data is incomplete!
_api        WARNING 	Driver  8: Car data is incomplete!
_api        WARNING 	Driver  9: Car data is incomplete!
_api        WARNING 	Driver 11: Car data is incomplete!
_api        WARNING 	Driver 15: Car data is incomplete!
_api        WARNING 	Driver 17: Car data is incomplete!
_api        WARNING 	Driver 19: Car data is incomplete!
_api        WARNING 	Driver 20: Car data is incomplete!
_api        WARNING 	Driver 21: Car data is incomplete!
_api        WARNING 	Driver 24: Car data is incomplete!
_api        WARNING 	Driver 25: Car data is incomplete!
_api        WARNING 	Driver 26: Car data is incomplete!
_api        WARNING 	Driver 28: Car data is incomplete!
_api        WARNING 	Driver 29: Car data is incomplete!
_api        WARNING 	Driver 44: Car data is incomplete!
_api        WARNING 	Driver 55: Car data is incomplete!
_api        WARNING 	Driver 63: Car data is incomplete!
_api        WARNING 	Driver 81: Car data is incomplete!
_api        WARNING 	Driver 87: Car data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
_api        WARNING 	Driver  1: Position data is incomplete!
_api        WARNING 	Driver  2: Position data is incomplete!
_api        WARNING 	Driver  3: Position data is incomplete!
_api        WARNING 	Driver  4: Position data is incomplete!
_api        WARNING 	Driver  5: Position data is incomplete!
_api        WARNING 	Driver  6: Position data is incomplete!
_api        WARNING 	Driver  7: Position data is incomplete!
_api        WARNING 	Driver  8: Position data is incomplete!
_api        WARNING 	Driver  9: Position data is incomplete!
_api        WARNING 	Driver 10: Position data is incomplete!
_api        WARNING 	Driver 11: Position data is incomplete!
_api        WARNING 	Driver 12: Position data is incomplete!
_api        WARNING 	Driver 14: Position data is incomplete!
_api        WARNING 	Driver 15: Position data is incomplete!
_api        WARNING 	Driver 16: Position data is incomplete!
_api        WARNING 	Driver 17: Position data is incomplete!
_api        WARNING 	Driver 18: Position data is incomplete!
_api        WARNING 	Driver 19: Position data is incomplete!
_api        WARNING 	Driver 20: Position data is incomplete!
_api        WARNING 	Driver 21: Position data is incomplete!
_api        WARNING 	Driver 22: Position data is incomplete!
_api        WARNING 	Driver 23: Position data is incomplete!
_api        WARNING 	Driver 24: Position data is incomplete!
_api        WARNING 	Driver 25: Position data is incomplete!
_api        WARNING 	Driver 26: Position data is incomplete!
_api        WARNING 	Driver 27: Position data is incomplete!
_api        WARNING 	Driver 28: Position data is incomplete!
_api        WARNING 	Driver 29: Position data is incomplete!
_api        WARNING 	Driver 44: Position data is incomplete!
_api        WARNING 	Driver 55: Position data is incomplete!
_api        WARNING 	Driver 63: Position data is incomplete!
_api        WARNING 	Driver 81: Position data is incomplete!
_api        WARNING 	Driver 87: Position data is incomplete!
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['4', '81', '1', '63', '22', '23', '16', '44', '10', '55', '6', '14', '18', '7', '5', '12', '27', '30', '31', '87']

In [37]:
qualifying_data_2025.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:16:54.443000,NOR,4,0 days 00:01:50.421000,1.0,1.0,0 days 00:15:08.068000,NaT,0 days 00:00:48.877000,0 days 00:00:24.492000,...,True,McLaren,0 days 00:15:08.068000,2025-03-15 05:02:39.667,1,NaN,False,,False,False
1,0 days 00:18:10.446000,NOR,4,0 days 00:01:16.003000,2.0,1.0,NaT,NaT,0 days 00:00:26.383000,0 days 00:00:17.285000,...,True,McLaren,0 days 00:16:54.443000,2025-03-15 05:04:26.042,1,NaN,False,,False,True
2,0 days 00:20:12.796000,NOR,4,0 days 00:02:02.350000,3.0,1.0,NaT,0 days 00:19:55.246000,0 days 00:00:37.180000,0 days 00:00:23.115000,...,True,McLaren,0 days 00:18:10.446000,2025-03-15 05:05:42.045,1,NaN,False,,False,False
3,0 days 00:22:09.056000,NOR,4,0 days 00:01:56.260000,4.0,2.0,0 days 00:20:16.711000,NaT,0 days 00:00:52.032000,0 days 00:00:23.199000,...,False,McLaren,0 days 00:20:12.796000,2025-03-15 05:07:44.395,1,NaN,False,,False,False
4,0 days 00:23:24.968000,NOR,4,0 days 00:01:15.912000,5.0,2.0,NaT,NaT,0 days 00:00:26.463000,0 days 00:00:17.116000,...,False,McLaren,0 days 00:22:09.056000,2025-03-15 05:09:40.655,1,NaN,False,,False,True

In [38]:
Quali_2025 = qualifying_data_2025.laps.pick_quicklaps()

Quali = Quali_2025.groupby("Driver")["LapTime"].min().dt.total_seconds()

In [44]:
Quali

Driver
ALB    75.737
ALO    76.288
ANT    76.525
BOR    76.516
DOO    76.315
GAS    75.980
HAD    76.175
HAM    75.919
HUL    76.579
LAW    77.094
LEC    75.755
NOR    75.096
OCO    77.147
PIA    75.180
RUS    75.546
SAI    75.931
STR    76.369
TSU    75.670
VER    75.481
Name: LapTime, dtype: float64

In [63]:
quali_df = Quali.reset_index()

In [64]:
quali_df.columns = ["Driver","QulaifyingTime (s)"]

In [65]:
quali_df

   Driver  QulaifyingTime (s)
0     ALB              75.737
1     ALO              76.288
2     ANT              76.525
3     BOR              76.516
4     DOO              76.315
5     GAS              75.980
6     HAD              76.175
7     HAM              75.919
8     HUL              76.579
9     LAW              77.094
10    LEC              75.755
11    NOR              75.096
12    OCO              77.147
13    PIA              75.180
14    RUS              75.546
15    SAI              75.931
16    STR              76.369
17    TSU              75.670
18    VER              75.481

In [66]:
qualifying_2025 = pd.DataFrame({
    "Driver":Driver,
    "QualifyingTime (s)":[
        #McLaren
        00,                 #NOR
        00,                 #PIA
        #Red Bull Racing
        00,                 #VER
        00,                 #HAD
        #Ferrari
        00,                 #LEC
        00,                 #HAM
        #Mercedes
        00,                 #RUS
        00,                 #ANT
        #Aston Martin Aramco
        00,                 #ALO
        00,                 #STR
        #Williams
        00,                 #ALB
        00,                 #SAI
        #Haas
        00,                 #OCO
        00,                 #BEA
        #Alpine
        00,                 #GAS
        00,                 #COL
        #Audi
        00,                 #HUL
        00,                 #BOR
        #Cadillac
        00,                 #PER
        00,                 #BOT
        #Racing Bulls
        00,                 #LAW
        00                  #LIN
    ]
})

In [67]:
qualifying_2025

   Driver  QualifyingTime (s)
0     NOR                   0
1     PIA                   0
2     VER                   0
3     HAD                   0
4     LEC                   0
5     HAM                   0
6     RUS                   0
7     ANT                   0
8     ALO                   0
9     STR                   0
10    ALB                   0
11    SAI                   0
12    OCO                   0
13    BEA                   0
14    GAS                   0
15    COL                   0
16    HUL                   0
17    BOR                   0
18    PER                   0
19    BOT                   0
20    LAW                   0
21    LIN                   0

In [68]:
qualifying_2025 = qualifying_2025.set_index("Driver")
quali_df = quali_df.set_index("Driver")

qualifying_2025 ["QualifyingTime (s)"] = quali_df["QulaifyingTime (s)"]
qualifying_2025.reset_index(inplace=True)
quali_df.reset_index(inplace=True)

In [69]:
qualifying_2025.fillna(0,inplace=True)

In [70]:
qualifying_2025

   Driver  QualifyingTime (s)
0     NOR              75.096
1     PIA              75.180
2     VER              75.481
3     HAD              76.175
4     LEC              75.755
5     HAM              75.919
6     RUS              75.546
7     ANT              76.525
8     ALO              76.288
9     STR              76.369
10    ALB              75.737
11    SAI              75.931
12    OCO              77.147
13    BEA               0.000
14    GAS              75.980
15    COL               0.000
16    HUL              76.579
17    BOR              76.516
18    PER               0.000
19    BOT               0.000
20    LAW              77.094
21    LIN               0.000

In [71]:
practice1 = fastf1.get_session(2025, 'Australia', 'FP1')
practice2 = fastf1.get_session(2025, 'Australia', 'FP2')
practice3 = fastf1.get_session(2025, 'Australia', 'FP3')

In [72]:
practice1.load()
practice2.load()
practice3.load()

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 2 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 87
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 87)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 3 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '16'
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '5', '6', '7', '10', '12', '14', '16', '18', '22', '23', '27', '30', '31', '44', '55', '63', '81', '87']

In [73]:
practice1.laps.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:17:15.002000,VER,1,0 days 00:01:58.029000,1.0,1.0,0 days 00:15:28.184000,NaT,0 days 00:00:50.194000,0 days 00:00:19.878000,...,True,Red Bull Racing,0 days 00:15:28.184000,2025-03-14 01:30:56.193,1,NaN,False,,False,False
1,0 days 00:18:34.773000,VER,1,0 days 00:01:19.771000,2.0,1.0,NaT,NaT,0 days 00:00:27.951000,0 days 00:00:17.793000,...,True,Red Bull Racing,0 days 00:17:15.002000,2025-03-14 01:32:43.011,1,NaN,False,,False,True
2,0 days 00:20:58.688000,VER,1,0 days 00:02:23.915000,3.0,1.0,NaT,NaT,0 days 00:00:49.204000,0 days 00:00:37.267000,...,True,Red Bull Racing,0 days 00:18:34.773000,2025-03-14 01:34:02.782,1,NaN,False,,False,True
3,0 days 00:22:17.837000,VER,1,0 days 00:01:19.149000,4.0,1.0,NaT,NaT,0 days 00:00:27.343000,0 days 00:00:17.455000,...,True,Red Bull Racing,0 days 00:20:58.688000,2025-03-14 01:36:26.697,1,NaN,False,,False,True
4,0 days 00:24:46.613000,VER,1,0 days 00:02:28.776000,5.0,1.0,NaT,NaT,0 days 00:00:51.751000,0 days 00:00:43.081000,...,True,Red Bull Racing,0 days 00:22:17.837000,2025-03-14 01:37:45.846,1,NaN,False,,False,True

In [74]:
practice1.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [75]:
plaps1 = practice1.laps.pick_quicklaps()

pbest_laps1 = plaps1.groupby("Driver")["LapTime"].min().dt.total_seconds()

print(pbest_laps1)

Driver
ALB    77.713
ALO    77.736
ANT    78.390
BEA    79.312
BOR    78.438
DOO    78.232
GAS    78.505
HAD    77.847
HAM    78.071
HUL    78.586
LAW    78.455
LEC    77.461
NOR    77.252
OCO    79.139
PIA    77.670
RUS    77.716
SAI    77.401
STR    78.057
TSU    78.061
VER    77.696
Name: LapTime, dtype: float64

In [76]:
plaps2 = practice2.laps.pick_quicklaps()

pbest_laps2 = plaps2.groupby("Driver")["LapTime"].min().dt.total_seconds()

print(pbest_laps2)

Driver
ALB    77.302
ALO    77.330
ANT    77.634
BOR    77.847
DOO    77.394
GAS    77.493
HAD    77.019
HAM    76.859
HUL    77.161
LAW    77.640
LEC    76.439
NOR    76.580
OCO    78.034
PIA    76.563
RUS    77.282
SAI    77.302
STR    77.279
TSU    76.784
VER    77.063
Name: LapTime, dtype: float64

In [77]:
plaps3 = practice3.laps.pick_quicklaps()

pbest_laps3 = plaps3.groupby("Driver")["LapTime"].min().dt.total_seconds()

print(pbest_laps3)

Driver
ALB    76.258
ALO    77.270
ANT    76.206
BOR    76.707
DOO    76.993
GAS    76.719
HAD    76.732
HAM    76.378
HUL    77.146
LEC    76.188
NOR    76.597
OCO    77.373
PIA    75.921
RUS    75.960
SAI    76.252
STR    76.948
TSU    76.455
VER    76.002
Name: LapTime, dtype: float64

In [78]:
pbest_laps1 = pbest_laps1.rename("FP1")
pbest_laps2 = pbest_laps2.rename("FP2")
pbest_laps3 = pbest_laps3.rename("FP3")

combined = pd.concat(
    [pbest_laps1, pbest_laps2, pbest_laps3],
    axis=1
)

In [79]:
combined

           FP1     FP2     FP3
Driver
ALB     77.713  77.302  76.258
ALO     77.736  77.330  77.270
ANT     78.390  77.634  76.206
BEA     79.312     NaN     NaN
BOR     78.438  77.847  76.707
DOO     78.232  77.394  76.993
GAS     78.505  77.493  76.719
HAD     77.847  77.019  76.732
HAM     78.071  76.859  76.378
HUL     78.586  77.161  77.146
LAW     78.455  77.640     NaN
LEC     77.461  76.439  76.188
NOR     77.252  76.580  76.597
OCO     79.139  78.034  77.373
PIA     77.670  76.563  75.921
RUS     77.716  77.282  75.960
SAI     77.401  77.302  76.252
STR     78.057  77.279  76.948
TSU     78.061  76.784  76.455
VER     77.696  77.063  76.002

In [90]:
combined["Best_Practice_Time"] = combined.min(axis=1)
combined

           FP1     FP2     FP3  Best_Practice_Time
Driver
ALB     77.713  77.302  76.258              76.258
ALO     77.736  77.330  77.270              77.270
ANT     78.390  77.634  76.206              76.206
BEA     79.312     NaN     NaN              79.312
BOR     78.438  77.847  76.707              76.707
DOO     78.232  77.394  76.993              76.993
GAS     78.505  77.493  76.719              76.719
HAD     77.847  77.019  76.732              76.732
HAM     78.071  76.859  76.378              76.378
HUL     78.586  77.161  77.146              77.146
LAW     78.455  77.640     NaN              77.640
LEC     77.461  76.439  76.188              76.188
NOR     77.252  76.580  76.597              76.580
OCO     79.139  78.034  77.373              77.373
PIA     77.670  76.563  75.921              75.921
RUS     77.716  77.282  75.960              75.960
SAI     77.401  77.302  76.252              76.252
STR     78.057  77.279  76.948              76.948
TSU     78.061  76.784  76.455              76.455
VER     77.696  77.063  76.002              76.002

In [84]:
clean_air_race_pace_2025 = {
    #McLaren
    "NOR":00,               #Lando Norris 🇬🇧
    "PIA":00,               #Oscar Piastri 🇦🇺
    #Red Bull Racing
    "VER":00,               #Max Verstappen 🇳🇱
    "HAD":00,               #Isack Hadjar 🇫🇷
    #Ferrari
    "LEC":00,               #Charles Leclerc 🇲🇨
    "HAM":00,               #Lewis Hamilton 🇬🇧
    #Mercedes
    "RUS":00,               #Geaorge Russell 🇬🇧
    "ANT":00,               #Andrea Kimi Antonelli 🇮🇹
    #Aston Martin Aramco
    "ALO":00,               #Fernando Alonso 🇪🇸
    "STR":00,               #Lance Stroll 🇨🇦
    #Williams
    "ALB":00,               #Alexander Albon 🇹🇭
    "SAI":00,               #Carlos Sainz Jr. 🇪🇸
    #Haas
    "OCO":00,               #Esteban Ocon 🇫🇷
    "BEA":00,               #Oliver Bearman 🇬🇧
    #Alpine
    "GAS":00,               #Piette Gasly 🇫🇷
    "COL":00,               #Franco Colapinto 🇦🇷
    #Audi
    "HUL":00,               #Nico Hulkenberg 🇩🇪
    "BOR":00,               #Gabriel Bortoleto 🇧🇷
    #Cadillac
    "PER":00,               #Sergio Perez 🇲🇽
    "BOT":00,               #Valtteri Bottas 🇫🇮
    #Racing Bulls
    "LAW":00,               #Liam Lawson 🇳🇿
    "LIN":00                #Arvid Lindblad 🇬🇧
}

In [87]:
clean_air_df = pd.DataFrame(list(clean_air_race_pace_2025.items()),columns=['Driver','Clean_air_pace_2025'])

In [89]:
clean_air_df

   Driver  Clean_air_pace_2025
0     NOR                    0
1     PIA                    0
2     VER                    0
3     HAD                    0
4     LEC                    0
5     HAM                    0
6     RUS                    0
7     ANT                    0
8     ALO                    0
9     STR                    0
10    ALB                    0
11    SAI                    0
12    OCO                    0
13    BEA                    0
14    GAS                    0
15    COL                    0
16    HUL                    0
17    BOR                    0
18    PER                    0
19    BOT                    0
20    LAW                    0
21    LIN                    0

In [91]:
clean_air_df = clean_air_df.set_index("Driver")
clean_air_df["Clean_air_pace_2025"] = combined["Best_Practice_Time"]
clean_air_df.reset_index(inplace=True)

In [93]:
clean_air_df.fillna(0,inplace=True)

In [101]:
clean_air_df

   Driver  Clean_air_pace_2025
0     NOR               76.580
1     PIA               75.921
2     VER               76.002
3     HAD               76.732
4     LEC               76.188
5     HAM               76.378
6     RUS               75.960
7     ANT               76.206
8     ALO               77.270
9     STR               76.948
10    ALB               76.258
11    SAI               76.252
12    OCO               77.373
13    BEA               79.312
14    GAS               76.719
15    COL                0.000
16    HUL               77.146
17    BOR               76.707
18    PER                0.000
19    BOT                0.000
20    LAW               77.640
21    LIN                0.000

In [95]:
team_points_2025 = {
    "McLaren":27,
    "Mercedes":27,
    "Red Bull":18,
    "Williams":10,
    "Ferrari":5,
    "Haas":00,
    "Aston Martin":8,
    "Racing Bulls":00,
    "Alpine":00,
    "Audi":00,
    "Cardillac":00
}

In [96]:
from sklearn.preprocessing import MinMaxScaler

teams_2025 = list(team_points_2025.keys())
points_2025 = np.array(list(team_points_2025.values())).reshape(-1,1)

scaler = MinMaxScaler()
scaled_points_2025 = scaler.fit_transform(points_2025)

team_performance_score_2025 = dict(zip(teams_2025, scaled_points_2025.flatten()))

In [97]:
qualifying_2025["Team"] = qualifying_2025["Driver"].map(driver_to_team)
qualifying_2025["TeamPerformanceScore"] = qualifying_2025["Team"].map(team_performance_score_2025)

In [100]:
qualifying_2025

   Driver  QualifyingTime (s)          Team  TeamPerformanceScore
0     NOR              75.096       McLaren              1.000000
1     PIA              75.180       McLaren              1.000000
2     VER              75.481      Red Bull              0.666667
3     HAD              76.175      Red Bull              0.666667
4     LEC              75.755       Ferrari              0.185185
5     HAM              75.919       Ferrari              0.185185
6     RUS              75.546      Mercedes              1.000000
7     ANT              76.525      Mercedes              1.000000
8     ALO              76.288  Aston Martin              0.296296
9     STR              76.369  Aston Martin              0.296296
10    ALB              75.737      Williams              0.370370
11    SAI              75.931      Williams              0.370370
12    OCO              77.147          Haas              0.000000
13    BEA               0.000          Haas              0.000000
14    GAS              75.980        Alpine              0.000000
15    COL               0.000        Alpine              0.000000
16    HUL              76.579          Audi              0.000000
17    BOR              76.516          Audi              0.000000
18    PER               0.000     Cardillac              0.000000
19    BOT               0.000     Cardillac              0.000000
20    LAW              77.094  Racing Bulls              0.000000
21    LIN               0.000  Racing Bulls              0.000000

In [102]:
clean_air_df = clean_air_df.set_index('Driver')
qualifying_2025 = qualifying_2025.set_index('Driver')

qualifying_2025["Clean_air_race_pace"] = clean_air_df["Clean_air_pace_2025"]

clean_air_df.reset_index(inplace=True)
qualifying_2025.reset_index(inplace=True)

In [110]:
qualifying_2025

,Driver,QualifyingTime (s),Team,TeamPerformanceScore,Clean_air_race_pace
0,NOR,75.096,McLaren,1.000000,76.580
1,PIA,75.180,McLaren,1.000000,75.921
2,VER,75.481,Red Bull,0.666667,76.002
3,HAD,76.175,Red Bull,0.666667,76.732
4,LEC,75.755,Ferrari,0.185185,76.188
5,HAM,75.919,Ferrari,0.185185,76.378
6,RUS,75.546,Mercedes,1.000000,75.960
7,ANT,76.525,Mercedes,1.000000,76.206
8,ALO,76.288,Aston Martin,0.296296,77.270
9,STR,76.369,Aston Martin,0.296296,76.948
10,ALB,75.737,Williams,0.370370,76.258
11,SAI,75.931,Williams,0.370370,76.252
12,OCO,77.147,Haas,0.000000,77.373
13,BEA,0.000,Haas,0.000000,79.312
14,GAS,75.980,Alpine,0.000000,76.719
15,COL,0.000,Alpine,0.000000,0.000
16,HUL,76.579,Audi,0.000000,77.146
17,BOR,76.516,Audi,0.000000,76.707
18,PER,0.000,Cardillac,0.000000,0.000
19,BOT,0.000,Cardillac,0.000000,0.000
20,LAW,77.094,Racing Bulls,0.000000,77.640
21,LIN,0.000,Racing Bulls,0.000000,0.000

In [104]:
merged_data1

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s),IsNewDriver
0,NOR,0,0,McLaren,0.0,85.973353,83.209877,103.165404,0
1,PIA,0,0,McLaren,0.0,86.659000,83.711877,101.717353,0
2,VER,0,0,Red Bull,0.0,85.153667,83.607000,103.032481,0
3,HAD,0,0,Red Bull,0.0,86.007451,84.444421,103.042538,1
4,LEC,0,0,Ferrari,0.0,86.007451,83.134895,103.461481,0
5,HAM,0,0,Ferrari,0.0,87.243885,84.624143,103.411115,0
6,RUS,0,0,Mercedes,0.0,93.307714,83.505891,103.283308,0
7,ANT,0,0,Mercedes,0.0,86.007451,84.444421,103.866679,1
8,ALO,0,0,Aston Martin,0.0,85.386098,84.444421,97.136643,0
9,STR,0,0,Aston Martin,0.0,85.691255,84.688246,104.074377,0
10,ALB,0,0,Williams,0.0,102.293600,84.573214,104.153094,0
11,SAI,0,0,Williams,0.0,85.745333,83.131018,84.438175,0
12,OCO,0,0,Haas,0.0,86.052000,85.438196,103.042538,0
13,BEA,0,0,Haas,0.0,86.007451,84.444421,102.994250,1
14,GAS,0,0,Alpine,0.0,85.607020,85.098071,104.337415,0
15,COL,0,0,Alpine,0.0,86.007451,84.444421,103.042538,1
16,HUL,0,0,Audi,0.0,86.041549,84.815368,104.051849,0
17,BOR,0,0,Audi,0.0,86.007451,84.444421,101.620450,1
18,PER,0,0,Cardillac,0.0,85.483961,84.047789,84.765875,0
19,BOT,0,0,Cardillac,0.0,86.879020,85.257250,86.068135,0
20,LAW,0,0,Racing Bulls,0.0,86.007451,84.444421,100.605146,1
21,LIN,0,0,Racing Bulls,0.0,86.007451,84.444421,103.042538,1

In [111]:
merged_data1 = merged_data1.set_index("Driver")
qualifying_2025 = qualifying_2025.set_index("Driver")

merged_data1[["QualifyingTime (s)","CleanAirRacePace (s)", "Team", "TeamPerformanceScore"]] = qualifying_2025[["QualifyingTime (s)","Clean_air_race_pace", "Team", "TeamPerformanceScore"]]

merged_data1.reset_index(inplace=True)
qualifying_2025.reset_index(inplace=True)

In [112]:
merged_data1

,Driver,QualifyingTime (s),CleanAirRacePace (s),Team,TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),TotalSectorTime_2025 (s),IsNewDriver
0,NOR,75.096,76.580,McLaren,1.000000,85.973353,83.209877,103.165404,0
1,PIA,75.180,75.921,McLaren,1.000000,86.659000,83.711877,101.717353,0
2,VER,75.481,76.002,Red Bull,0.666667,85.153667,83.607000,103.032481,0
3,HAD,76.175,76.732,Red Bull,0.666667,86.007451,84.444421,103.042538,1
4,LEC,75.755,76.188,Ferrari,0.185185,86.007451,83.134895,103.461481,0
5,HAM,75.919,76.378,Ferrari,0.185185,87.243885,84.624143,103.411115,0
6,RUS,75.546,75.960,Mercedes,1.000000,93.307714,83.505891,103.283308,0
7,ANT,76.525,76.206,Mercedes,1.000000,86.007451,84.444421,103.866679,1
8,ALO,76.288,77.270,Aston Martin,0.296296,85.386098,84.444421,97.136643,0
9,STR,76.369,76.948,Aston Martin,0.296296,85.691255,84.688246,104.074377,0
10,ALB,75.737,76.258,Williams,0.370370,102.293600,84.573214,104.153094,0
11,SAI,75.931,76.252,Williams,0.370370,85.745333,83.131018,84.438175,0
12,OCO,77.147,77.373,Haas,0.000000,86.052000,85.438196,103.042538,0
13,BEA,0.000,79.312,Haas,0.000000,86.007451,84.444421,102.994250,1
14,GAS,75.980,76.719,Alpine,0.000000,85.607020,85.098071,104.337415,0
15,COL,0.000,0.000,Alpine,0.000000,86.007451,84.444421,103.042538,1
16,HUL,76.579,77.146,Audi,0.000000,86.041549,84.815368,104.051849,0
17,BOR,76.516,76.707,Audi,0.000000,86.007451,84.444421,101.620450,1
18,PER,0.000,0.000,Cardillac,0.000000,85.483961,84.047789,84.765875,0
19,BOT,0.000,0.000,Cardillac,0.000000,86.879020,85.257250,86.068135,0
20,LAW,77.094,77.640,Racing Bulls,0.000000,86.007451,84.444421,100.605146,1
21,LIN,0.000,0.000,Racing Bulls,0.000000,86.007451,84.444421,103.042538,1

In [177]:
merged_data1.columns

Index(['Driver', 'QualifyingTime (s)', 'CleanAirRacePace (s)', 'Team',
       'TeamPerformanceScore', 'TotalSectorTime_2023 (s)',
       'TotalSectorTime_2024 (s)', 'TotalSectorTime_2025 (s)', 'IsNewDriver'],
      dtype='object')

## Defining Features (X) and Target (y)

In [179]:
X = merged_data1[[
    'QualifyingTime (s)', 'CleanAirRacePace (s)', 
       'TeamPerformanceScore', 'TotalSectorTime_2023 (s)',
       'TotalSectorTime_2024 (s)', 'IsNewDriver'
]]

In [180]:
X

,QualifyingTime (s),CleanAirRacePace (s),TeamPerformanceScore,TotalSectorTime_2023 (s),TotalSectorTime_2024 (s),IsNewDriver
0,63.971,64.324,1.000000,72.480386,71.709254,0
1,64.492,64.442,1.000000,73.628261,71.253629,0
2,64.929,64.534,0.433155,72.228114,71.685729,0
3,65.226,65.547,0.433155,72.695271,72.017786,1
4,64.492,0.000,0.489305,72.277514,72.110986,0
5,64.582,64.790,0.489305,72.695271,71.587143,0
6,64.763,65.018,0.532086,72.680000,71.262814,0
7,65.276,65.053,0.532086,72.695271,72.017786,1
8,65.128,65.243,0.058824,72.510686,72.906522,0
9,65.329,65.022,0.058824,72.875314,72.346377,0
10,65.205,65.243,0.147059,73.004629,72.364594,0
11,65.582,65.326,0.147059,72.476043,71.312500,0
12,65.364,65.519,0.074866,73.197551,72.191714,0
13,65.312,65.366,0.074866,72.695271,72.017786,1
14,65.649,65.366,0.029412,72.841500,72.077929,0
15,65.288,65.546,0.029412,72.695271,72.017786,1
16,65.606,65.283,0.000000,81.352818,71.978086,0
17,65.132,65.182,0.000000,72.695271,72.017786,1
18,0.000,0.000,0.000000,72.194571,72.017786,0
19,0.000,0.000,0.000000,73.541478,72.481957,0
20,64.926,65.182,0.074866,72.695271,72.017786,1
21,0.000,0.000,0.074866,72.695271,72.017786,1

In [ ]:
y =

In [87]:
y

Driver
NOR    71.709254
PIA    71.253629
VER    71.685729
HAD          NaN
LEC    72.110986
HAM    71.587143
RUS    71.262814
ANT          NaN
ALO    72.906522
STR    72.346377
ALB    72.364594
SAI    71.312500
OCO    72.191714
BEA          NaN
GAS    72.077929
COL          NaN
HUL    71.978086
BOR          NaN
PER    72.017786
BOT    72.481957
LAW          NaN
LIN          NaN
Name: LapTime (s), dtype: float64