In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

In [3]:
Aus = pd.read_csv('Data/AustraliaGP.csv')

In [4]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847,81.664,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943,80.324,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326,80.778,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668,80.459,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660,83.514,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619,81.413,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167,81.071,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941,80.137,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050,79.669,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351,81.067,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358,80.890,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291,79.827,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922,80.838,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794,80.443,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179,80.983,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,NaN,84.397,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729,80.087,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049,79.053,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253,NaN,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,NaN,NaN,15.0,0,19.88
19,VER,80.789,80.366,80.197,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,NaN,NaN,6.0,0,19.88

In [5]:
Aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Driver              20 non-null     object
 1   FP1_BestTime(s)     20 non-null     float64
 2   FP2_BestTime(s)     19 non-null     float64
 3   FP3_BestTime(s)     19 non-null     float64
 4   Sector1Time(s)      20 non-null     float64
 5   Sector2Time(s)      20 non-null     float64
 6   Sector3Time(s)      20 non-null     float64
 7   Average_Laptime(s)  20 non-null     float64
 8   Longest_Stint       20 non-null     int64
 9   Tyre_Compound       20 non-null     object
 10  Qualifying_Time(s)  18 non-null     float64
 11  Starting_Pos        18 non-null     float64
 12  Race_Result         20 non-null     float64
 13  rain_probability    20 non-null     int64
 14  Temprature          20 non-null     float64
dtypes: float64(11), int64(2), object(2)
memory usage: 2.5+ KB

In [9]:
imputer = SimpleImputer(strategy='mean')
Aus['FP2_BestTime(s)'] = imputer.fit_transform(Aus[['FP2_BestTime(s)']])
Aus['FP3_BestTime(s)'] = imputer.fit_transform(Aus[['FP3_BestTime(s)']])

In [10]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,NaN,NaN,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,NaN,NaN,6.0,0,19.88

In [11]:
Aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Driver              20 non-null     object
 1   FP1_BestTime(s)     20 non-null     float64
 2   FP2_BestTime(s)     20 non-null     float64
 3   FP3_BestTime(s)     20 non-null     float64
 4   Sector1Time(s)      20 non-null     float64
 5   Sector2Time(s)      20 non-null     float64
 6   Sector3Time(s)      20 non-null     float64
 7   Average_Laptime(s)  20 non-null     float64
 8   Longest_Stint       20 non-null     int64
 9   Tyre_Compound       20 non-null     object
 10  Qualifying_Time(s)  18 non-null     float64
 11  Starting_Pos        18 non-null     float64
 12  Race_Result         20 non-null     float64
 13  rain_probability    20 non-null     int64
 14  Temprature          20 non-null     float64
dtypes: float64(11), int64(2), object(2)
memory usage: 2.5+ KB

In [12]:
Aus['Qualifying_Time(s)'].max()

np.float64(83.244)

In [14]:
Aus['Qualifying_Time(s)'].fillna(Aus['Qualifying_Time(s)'].max(),inplace=True)

/tmp/ipykernel_893373/3187032826.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Aus['Qualifying_Time(s)'].fillna(Aus['Qualifying_Time(s)'].max(),inplace=True)

In [15]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,83.244,NaN,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,83.244,NaN,6.0,0,19.88

In [17]:
Aus['Starting_Pos'].fillna(20,inplace=True)

/tmp/ipykernel_893373/367777916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Aus['Starting_Pos'].fillna(20,inplace=True)

In [18]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,83.244,20.0,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,83.244,20.0,6.0,0,19.88