In [84]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

# Australia GP (For Training)

In [3]:
Aus = pd.read_csv('Data/AustraliaGP.csv')

In [4]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847,81.664,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943,80.324,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326,80.778,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668,80.459,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660,83.514,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619,81.413,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167,81.071,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941,80.137,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050,79.669,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351,81.067,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358,80.890,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291,79.827,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922,80.838,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794,80.443,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179,80.983,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,NaN,84.397,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729,80.087,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049,79.053,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253,NaN,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,NaN,NaN,15.0,0,19.88
19,VER,80.789,80.366,80.197,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,NaN,NaN,6.0,0,19.88

In [5]:
Aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Driver              20 non-null     object
 1   FP1_BestTime(s)     20 non-null     float64
 2   FP2_BestTime(s)     19 non-null     float64
 3   FP3_BestTime(s)     19 non-null     float64
 4   Sector1Time(s)      20 non-null     float64
 5   Sector2Time(s)      20 non-null     float64
 6   Sector3Time(s)      20 non-null     float64
 7   Average_Laptime(s)  20 non-null     float64
 8   Longest_Stint       20 non-null     int64
 9   Tyre_Compound       20 non-null     object
 10  Qualifying_Time(s)  18 non-null     float64
 11  Starting_Pos        18 non-null     float64
 12  Race_Result         20 non-null     float64
 13  rain_probability    20 non-null     int64
 14  Temprature          20 non-null     float64
dtypes: float64(11), int64(2), object(2)
memory usage: 2.5+ KB

In [9]:
imputer = SimpleImputer(strategy='mean')
Aus['FP2_BestTime(s)'] = imputer.fit_transform(Aus[['FP2_BestTime(s)']])
Aus['FP3_BestTime(s)'] = imputer.fit_transform(Aus[['FP3_BestTime(s)']])

In [10]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,NaN,NaN,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,NaN,NaN,6.0,0,19.88

In [11]:
Aus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Driver              20 non-null     object
 1   FP1_BestTime(s)     20 non-null     float64
 2   FP2_BestTime(s)     20 non-null     float64
 3   FP3_BestTime(s)     20 non-null     float64
 4   Sector1Time(s)      20 non-null     float64
 5   Sector2Time(s)      20 non-null     float64
 6   Sector3Time(s)      20 non-null     float64
 7   Average_Laptime(s)  20 non-null     float64
 8   Longest_Stint       20 non-null     int64
 9   Tyre_Compound       20 non-null     object
 10  Qualifying_Time(s)  18 non-null     float64
 11  Starting_Pos        18 non-null     float64
 12  Race_Result         20 non-null     float64
 13  rain_probability    20 non-null     int64
 14  Temprature          20 non-null     float64
dtypes: float64(11), int64(2), object(2)
memory usage: 2.5+ KB

In [12]:
Aus['Qualifying_Time(s)'].max()

np.float64(83.244)

In [14]:
Aus['Qualifying_Time(s)'].fillna(Aus['Qualifying_Time(s)'].max(),inplace=True)

/tmp/ipykernel_893373/3187032826.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Aus['Qualifying_Time(s)'].fillna(Aus['Qualifying_Time(s)'].max(),inplace=True)

In [15]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,83.244,NaN,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,83.244,NaN,6.0,0,19.88

In [17]:
Aus['Starting_Pos'].fillna(20,inplace=True)

/tmp/ipykernel_893373/367777916.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Aus['Starting_Pos'].fillna(20,inplace=True)

In [18]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0,0,19.88
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0,0,19.88
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0,0,19.88
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0,0,19.88
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0,0,19.88
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0,0,19.88
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0,0,19.88
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0,0,19.88
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0,0,19.88
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0,0,19.88
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0,0,19.88
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0,0,19.88
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0,0,19.88
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0,0,19.88
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0,0,19.88
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0,0,19.88
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0,0,19.88
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0,0,19.88
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,83.244,20.0,15.0,0,19.88
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,83.244,20.0,6.0,0,19.88

In [24]:
Aus = pd.get_dummies(Aus, columns=["Tyre_Compound"], drop_first=True)

In [25]:
Aus

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Qualifying_Time(s),Starting_Pos,Race_Result,rain_probability,Temprature,Tyre_Compound_MEDIUM,Tyre_Compound_SOFT
0,ALB,83.130,81.847000,81.664000,36.650031,20.898312,42.942393,100.398929,11,80.941,15.0,12.0,0,19.88,False,False
1,ANT,81.376,79.943000,80.324000,36.042935,19.788161,41.798556,95.665077,15,78.811,2.0,2.0,0,19.88,False,False
2,BEA,82.682,81.326000,80.778000,39.039839,20.835774,41.873786,102.072750,15,80.311,12.0,7.0,0,19.88,False,False
3,BOR,81.696,81.668000,80.459000,39.209964,20.777286,46.708920,99.549182,9,80.221,10.0,9.0,0,19.88,True,False
4,BOT,84.022,83.660000,83.514000,37.285821,20.556821,43.604600,101.500360,15,83.244,19.0,19.0,0,19.88,True,False
5,COL,83.325,82.619000,81.413000,38.297846,22.258222,45.171583,101.418318,11,81.270,16.0,14.0,0,19.88,True,False
6,GAS,84.035,82.167000,81.071000,37.261133,22.742125,41.458429,99.050308,11,80.501,14.0,10.0,0,19.88,True,False
7,HAD,81.087,80.941000,80.137000,36.938357,23.917321,42.749958,99.028217,13,79.303,3.0,20.0,0,19.88,True,False
8,HAM,80.736,80.050000,79.669000,36.481677,21.753969,43.648655,99.920000,13,79.478,7.0,4.0,0,19.88,False,False
9,HUL,81.969,81.351000,81.067000,34.139485,20.528765,41.426839,93.962483,10,80.303,11.0,22.0,0,19.88,True,False
10,LAW,82.613,81.358000,80.890000,35.426966,21.766172,41.597720,97.647800,14,79.994,8.0,13.0,0,19.88,True,False
11,LEC,80.267,80.291000,79.827000,37.004633,20.809667,45.400444,99.486360,10,79.327,4.0,3.0,0,19.88,False,False
12,LIN,81.313,80.922000,80.838000,39.199867,20.971933,43.092519,101.070296,15,81.247,9.0,8.0,0,19.88,False,True
13,NOR,84.391,80.794000,80.443000,33.216286,20.360862,42.638692,92.236042,16,79.475,6.0,5.0,0,19.88,False,True
14,OCO,82.161,81.179000,80.983000,39.771345,20.526621,45.612115,102.046375,10,80.491,13.0,11.0,0,19.88,False,False
15,PER,84.620,81.184895,84.397000,40.033500,21.311000,53.610000,118.806000,2,82.605,18.0,16.0,0,19.88,False,True
16,PIA,81.342,79.729000,80.087000,36.638115,20.288808,43.384000,96.971182,10,79.380,5.0,21.0,0,19.88,False,False
17,RUS,81.371,80.049000,79.053000,38.616071,20.045714,42.000042,101.140833,13,78.518,1.0,1.0,0,19.88,False,False
18,SAI,82.323,82.253000,80.884789,35.224000,21.142100,44.954667,102.363111,7,83.244,20.0,15.0,0,19.88,True,False
19,VER,80.789,80.366000,80.197000,37.872231,19.745000,41.107000,93.862300,5,83.244,20.0,6.0,0,19.88,True,False

In [90]:
Aus.to_csv('AustraliaGPModified.csv',index=False)

# Japan GP (For Prediction)

In [85]:
Jap = pd.read_csv('Data/JapanGP.csv')

In [86]:
Jap

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,rain_probability,Temprature
0,ALB,93.697,91.496,91.733,42.531231,48.057667,21.567000,106.666583,11.0,MEDIUM,91.088,17.0,0,14.79
1,ANT,91.692,90.225,89.362,47.109174,45.386107,21.655821,103.388474,10.0,MEDIUM,88.778,1.0,0,14.79
2,BEA,92.900,91.498,91.558,43.953800,45.669714,22.014214,102.402952,15.0,MEDIUM,91.090,18.0,0,14.79
3,BOR,92.759,91.933,91.000,53.260667,48.081545,24.916545,119.585250,7.0,SOFT,90.274,9.0,0,14.79
4,BOT,94.490,92.615,92.503,43.989200,47.002679,21.424036,109.386375,15.0,MEDIUM,92.330,20.0,0,14.79
5,COL,93.361,92.438,91.759,43.006280,47.661536,21.347107,104.757091,14.0,MEDIUM,90.627,15.0,0,14.79
6,CRA,96.362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,14.79
7,GAS,92.978,91.734,91.082,41.008560,46.617310,21.627517,106.528667,13.0,HARD,89.691,7.0,0,14.79
8,HAD,92.803,91.759,91.094,45.154038,46.109931,21.571241,106.243957,14.0,HARD,89.978,8.0,0,14.79
9,HAM,92.040,90.980,90.383,46.753333,49.164185,22.050000,104.465000,9.0,MEDIUM,89.567,6.0,0,14.79
10,HUL,92.798,91.441,90.658,42.662375,45.554074,22.005074,104.905045,8.0,HARD,90.387,13.0,0,14.79
11,LAW,92.529,91.590,91.097,42.420000,47.320533,21.645833,107.318542,14.0,MEDIUM,90.495,14.0,0,14.79
12,LEC,91.955,90.846,90.229,43.150960,46.994536,22.093107,107.622043,12.0,MEDIUM,89.405,4.0,0,14.79
13,LIN,92.665,NaN,91.288,NaN,69.262000,38.967000,NaN,1.0,MEDIUM,90.319,10.0,0,14.79
14,NOR,91.798,90.649,90.600,45.334286,46.782176,24.024941,108.705583,9.0,SOFT,89.409,5.0,0,14.79
15,OCO,92.601,91.532,91.326,43.407370,46.763433,21.440467,104.676208,15.0,MEDIUM,90.309,12.0,0,14.79
16,PER,94.221,93.689,92.540,47.314417,45.573786,22.538429,106.543600,9.0,HARD,92.206,19.0,0,14.79
17,PIA,91.865,90.133,90.364,42.560769,45.652448,21.447586,105.411958,10.0,MEDIUM,89.132,3.0,0,14.79
18,RUS,91.666,90.338,89.616,47.393800,45.788276,22.059000,107.931045,9.0,MEDIUM,89.076,2.0,0,14.79
19,SAI,93.383,91.608,91.829,42.486538,46.049067,20.790467,105.217167,12.0,HARD,91.033,16.0,0,14.79
20,STR,95.294,93.951,93.485,44.378000,47.618476,21.998000,114.290000,7.0,SOFT,92.920,22.0,0,14.79
21,VER,92.457,91.509,90.910,43.427846,44.212276,21.476103,103.802417,18.0,HARD,90.262,11.0,0,14.79

In [87]:
Jap = Jap[Jap["Starting_Pos"].notna()]

In [88]:
Jap

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,rain_probability,Temprature
0,ALB,93.697,91.496,91.733,42.531231,48.057667,21.567000,106.666583,11.0,MEDIUM,91.088,17.0,0,14.79
1,ANT,91.692,90.225,89.362,47.109174,45.386107,21.655821,103.388474,10.0,MEDIUM,88.778,1.0,0,14.79
2,BEA,92.900,91.498,91.558,43.953800,45.669714,22.014214,102.402952,15.0,MEDIUM,91.090,18.0,0,14.79
3,BOR,92.759,91.933,91.000,53.260667,48.081545,24.916545,119.585250,7.0,SOFT,90.274,9.0,0,14.79
4,BOT,94.490,92.615,92.503,43.989200,47.002679,21.424036,109.386375,15.0,MEDIUM,92.330,20.0,0,14.79
5,COL,93.361,92.438,91.759,43.006280,47.661536,21.347107,104.757091,14.0,MEDIUM,90.627,15.0,0,14.79
7,GAS,92.978,91.734,91.082,41.008560,46.617310,21.627517,106.528667,13.0,HARD,89.691,7.0,0,14.79
8,HAD,92.803,91.759,91.094,45.154038,46.109931,21.571241,106.243957,14.0,HARD,89.978,8.0,0,14.79
9,HAM,92.040,90.980,90.383,46.753333,49.164185,22.050000,104.465000,9.0,MEDIUM,89.567,6.0,0,14.79
10,HUL,92.798,91.441,90.658,42.662375,45.554074,22.005074,104.905045,8.0,HARD,90.387,13.0,0,14.79
11,LAW,92.529,91.590,91.097,42.420000,47.320533,21.645833,107.318542,14.0,MEDIUM,90.495,14.0,0,14.79
12,LEC,91.955,90.846,90.229,43.150960,46.994536,22.093107,107.622043,12.0,MEDIUM,89.405,4.0,0,14.79
13,LIN,92.665,NaN,91.288,NaN,69.262000,38.967000,NaN,1.0,MEDIUM,90.319,10.0,0,14.79
14,NOR,91.798,90.649,90.600,45.334286,46.782176,24.024941,108.705583,9.0,SOFT,89.409,5.0,0,14.79
15,OCO,92.601,91.532,91.326,43.407370,46.763433,21.440467,104.676208,15.0,MEDIUM,90.309,12.0,0,14.79
16,PER,94.221,93.689,92.540,47.314417,45.573786,22.538429,106.543600,9.0,HARD,92.206,19.0,0,14.79
17,PIA,91.865,90.133,90.364,42.560769,45.652448,21.447586,105.411958,10.0,MEDIUM,89.132,3.0,0,14.79
18,RUS,91.666,90.338,89.616,47.393800,45.788276,22.059000,107.931045,9.0,MEDIUM,89.076,2.0,0,14.79
19,SAI,93.383,91.608,91.829,42.486538,46.049067,20.790467,105.217167,12.0,HARD,91.033,16.0,0,14.79
20,STR,95.294,93.951,93.485,44.378000,47.618476,21.998000,114.290000,7.0,SOFT,92.920,22.0,0,14.79
21,VER,92.457,91.509,90.910,43.427846,44.212276,21.476103,103.802417,18.0,HARD,90.262,11.0,0,14.79

In [91]:
Jap['FP2_BestTime(s)'] = imputer.fit_transform(Jap[['FP2_BestTime(s)']])
Jap['Sector1Time(s)'] = imputer.fit_transform(Jap[['Sector1Time(s)']])
Jap['Average_Laptime(s)'] = imputer.fit_transform(Jap[['Average_Laptime(s)']])

/tmp/ipykernel_893373/999907501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Jap['FP2_BestTime(s)'] = imputer.fit_transform(Jap[['FP2_BestTime(s)']])
/tmp/ipykernel_893373/999907501.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Jap['Sector1Time(s)'] = imputer.fit_transform(Jap[['Sector1Time(s)']])
/tmp/ipykernel_893373/999907501.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Jap['Average_Laptime(s)'] = imputer.fit_transform(Jap[['Average_Laptime(s)']])

In [92]:
Jap

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,rain_probability,Temprature
0,ALB,93.697,91.4960,91.733,42.531231,48.057667,21.567000,106.666583,11.0,MEDIUM,91.088,17.0,0,14.79
1,ANT,91.692,90.2250,89.362,47.109174,45.386107,21.655821,103.388474,10.0,MEDIUM,88.778,1.0,0,14.79
2,BEA,92.900,91.4980,91.558,43.953800,45.669714,22.014214,102.402952,15.0,MEDIUM,91.090,18.0,0,14.79
3,BOR,92.759,91.9330,91.000,53.260667,48.081545,24.916545,119.585250,7.0,SOFT,90.274,9.0,0,14.79
4,BOT,94.490,92.6150,92.503,43.989200,47.002679,21.424036,109.386375,15.0,MEDIUM,92.330,20.0,0,14.79
5,COL,93.361,92.4380,91.759,43.006280,47.661536,21.347107,104.757091,14.0,MEDIUM,90.627,15.0,0,14.79
7,GAS,92.978,91.7340,91.082,41.008560,46.617310,21.627517,106.528667,13.0,HARD,89.691,7.0,0,14.79
8,HAD,92.803,91.7590,91.094,45.154038,46.109931,21.571241,106.243957,14.0,HARD,89.978,8.0,0,14.79
9,HAM,92.040,90.9800,90.383,46.753333,49.164185,22.050000,104.465000,9.0,MEDIUM,89.567,6.0,0,14.79
10,HUL,92.798,91.4410,90.658,42.662375,45.554074,22.005074,104.905045,8.0,HARD,90.387,13.0,0,14.79
11,LAW,92.529,91.5900,91.097,42.420000,47.320533,21.645833,107.318542,14.0,MEDIUM,90.495,14.0,0,14.79
12,LEC,91.955,90.8460,90.229,43.150960,46.994536,22.093107,107.622043,12.0,MEDIUM,89.405,4.0,0,14.79
13,LIN,92.665,91.5982,91.288,44.565132,69.262000,38.967000,106.992398,1.0,MEDIUM,90.319,10.0,0,14.79
14,NOR,91.798,90.6490,90.600,45.334286,46.782176,24.024941,108.705583,9.0,SOFT,89.409,5.0,0,14.79
15,OCO,92.601,91.5320,91.326,43.407370,46.763433,21.440467,104.676208,15.0,MEDIUM,90.309,12.0,0,14.79
16,PER,94.221,93.6890,92.540,47.314417,45.573786,22.538429,106.543600,9.0,HARD,92.206,19.0,0,14.79
17,PIA,91.865,90.1330,90.364,42.560769,45.652448,21.447586,105.411958,10.0,MEDIUM,89.132,3.0,0,14.79
18,RUS,91.666,90.3380,89.616,47.393800,45.788276,22.059000,107.931045,9.0,MEDIUM,89.076,2.0,0,14.79
19,SAI,93.383,91.6080,91.829,42.486538,46.049067,20.790467,105.217167,12.0,HARD,91.033,16.0,0,14.79
20,STR,95.294,93.9510,93.485,44.378000,47.618476,21.998000,114.290000,7.0,SOFT,92.920,22.0,0,14.79
21,VER,92.457,91.5090,90.910,43.427846,44.212276,21.476103,103.802417,18.0,HARD,90.262,11.0,0,14.79

In [94]:
Jap = pd.get_dummies(Jap, columns=["Tyre_Compound"], drop_first=True)

In [95]:
Jap

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Qualifying_Time(s),Starting_Pos,rain_probability,Temprature,Tyre_Compound_MEDIUM,Tyre_Compound_SOFT
0,ALB,93.697,91.4960,91.733,42.531231,48.057667,21.567000,106.666583,11.0,91.088,17.0,0,14.79,True,False
1,ANT,91.692,90.2250,89.362,47.109174,45.386107,21.655821,103.388474,10.0,88.778,1.0,0,14.79,True,False
2,BEA,92.900,91.4980,91.558,43.953800,45.669714,22.014214,102.402952,15.0,91.090,18.0,0,14.79,True,False
3,BOR,92.759,91.9330,91.000,53.260667,48.081545,24.916545,119.585250,7.0,90.274,9.0,0,14.79,False,True
4,BOT,94.490,92.6150,92.503,43.989200,47.002679,21.424036,109.386375,15.0,92.330,20.0,0,14.79,True,False
5,COL,93.361,92.4380,91.759,43.006280,47.661536,21.347107,104.757091,14.0,90.627,15.0,0,14.79,True,False
7,GAS,92.978,91.7340,91.082,41.008560,46.617310,21.627517,106.528667,13.0,89.691,7.0,0,14.79,False,False
8,HAD,92.803,91.7590,91.094,45.154038,46.109931,21.571241,106.243957,14.0,89.978,8.0,0,14.79,False,False
9,HAM,92.040,90.9800,90.383,46.753333,49.164185,22.050000,104.465000,9.0,89.567,6.0,0,14.79,True,False
10,HUL,92.798,91.4410,90.658,42.662375,45.554074,22.005074,104.905045,8.0,90.387,13.0,0,14.79,False,False
11,LAW,92.529,91.5900,91.097,42.420000,47.320533,21.645833,107.318542,14.0,90.495,14.0,0,14.79,True,False
12,LEC,91.955,90.8460,90.229,43.150960,46.994536,22.093107,107.622043,12.0,89.405,4.0,0,14.79,True,False
13,LIN,92.665,91.5982,91.288,44.565132,69.262000,38.967000,106.992398,1.0,90.319,10.0,0,14.79,True,False
14,NOR,91.798,90.6490,90.600,45.334286,46.782176,24.024941,108.705583,9.0,89.409,5.0,0,14.79,False,True
15,OCO,92.601,91.5320,91.326,43.407370,46.763433,21.440467,104.676208,15.0,90.309,12.0,0,14.79,True,False
16,PER,94.221,93.6890,92.540,47.314417,45.573786,22.538429,106.543600,9.0,92.206,19.0,0,14.79,False,False
17,PIA,91.865,90.1330,90.364,42.560769,45.652448,21.447586,105.411958,10.0,89.132,3.0,0,14.79,True,False
18,RUS,91.666,90.3380,89.616,47.393800,45.788276,22.059000,107.931045,9.0,89.076,2.0,0,14.79,True,False
19,SAI,93.383,91.6080,91.829,42.486538,46.049067,20.790467,105.217167,12.0,91.033,16.0,0,14.79,False,False
20,STR,95.294,93.9510,93.485,44.378000,47.618476,21.998000,114.290000,7.0,92.920,22.0,0,14.79,False,True
21,VER,92.457,91.5090,90.910,43.427846,44.212276,21.476103,103.802417,18.0,90.262,11.0,0,14.79,False,False

In [96]:
Jap.to_csv('JapanGPModified.csv',index=False)