In [2]:
import pandas as pd
import numpy as np
import fastf1
import requests

### Function to get Best FP1 Time

In [3]:
def get_fp1_best(FP1):

    laps = FP1.laps.pick_quicklaps()

    best = laps.groupby("Driver")["LapTime"].min().dt.total_seconds().reset_index()

    return best

### Function to get Best FP2 Time

In [4]:
def get_fp2_best(FP2):

    laps = FP2.laps.pick_quicklaps()

    best = laps.groupby("Driver")["LapTime"].min().dt.total_seconds().reset_index()

    return best

### Function to get Best FP3 Time

In [5]:
def get_fp3_best(FP3):

    laps = FP3.laps.pick_quicklaps()

    best = laps.groupby("Driver")["LapTime"].min().dt.total_seconds().reset_index()

    return best

In [6]:
def get_sector_times (FP2):

    laps = FP2.laps

    sector_times = laps.groupby("Driver")[[
    "Sector1Time",
    "Sector2Time",
    "Sector3Time"
    ]].mean().apply(lambda x: x.dt.total_seconds()).reset_index()

    return sector_times

In [7]:
def get_average_laptime (FP2):

    laps = FP2.laps

    avg_lap = laps.groupby("Driver")["LapTime"].mean().dt.total_seconds().reset_index()

    return avg_lap

In [8]:
def get_stint(FP2):

    laps = FP2.laps

    stints = (
        laps.groupby(["Driver","Stint"])
        .size()
        .reset_index(name="LapCount")
    )

    longest_stint = (
        stints.groupby("Driver")["LapCount"]
        .max()
        .reset_index(name="LongestStint")
    )

    return longest_stint

In [9]:
def get_tyre_compound (FP2):

    laps = FP2.laps

    tyres = laps.groupby("Driver")["Compound"].agg(lambda x: x.mode()[0]).reset_index()

    return tyres

In [10]:
def get_qualifying_data(Qualify):

    results = Qualify.results.copy()

    qual_time = results[["Q3", "Q2", "Q1"]].bfill(axis=1).iloc[:, 0]

    qual = results[["Abbreviation"]].copy()
    qual["Qualifying_Time(s)"] = qual_time.dt.total_seconds()

    qual.rename(columns={"Abbreviation": "Driver"}, inplace=True)

    return qual

In [11]:
def get_starting_position(Qualify):

    quali_results = Qualify.results[['Abbreviation', 'Position']]
    quali_results.rename(columns={"Abbreviation":"Driver"},inplace=True)

    return quali_results

In [12]:
def get_race_results(Result):

    race = Result.results[["Abbreviation","Position"]]
    race.rename(columns={"Abbreviation":"Driver"},inplace=True)

    return race

In [13]:
def Rain(API_KEY,lat,lon,forecast_time):
    url = f"http://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API_KEY}&units=metric"

    response = requests.get(url)
    data = response.json()

    if "list" not in data:
        print("API ERROR:", data)
    else:

        forecast_data = next(
            (f for f in data["list"] if f["dt_txt"] == forecast_time),
            None
        )
        if forecast_data:
            rain_probability = forecast_data.get("pop", 0)
            temperature = forecast_data["main"]["temp"]
        else:
            forecast_data = data["list"][0]
            rain_probability = forecast_data.get("pop", 0)
            temperature = forecast_data["main"]["temp"]

    return rain_probability,temperature

# Australia GP Data(For Training)

In [13]:
season = 2026
race = 'Australia'

FP1 = fastf1.get_session(season, race, 'FP1')
FP1.load()
FP2 = fastf1.get_session(season, race, 'FP2')
FP2.load()
FP3 = fastf1.get_session(season, race, 'FP3')
FP3.load()

Qualify = fastf1.get_session(season, race, 'Q')
Qualify.load()

Result = fastf1.get_session(season, race, 'R')
Result.load()

print(f"Done Loading Season {season} & Race {race}")

fp1_best = get_fp1_best(FP1)
fp2_best = get_fp2_best(FP2)
fp3_best = get_fp3_best(FP3)
sector_time_best = get_sector_times(FP2)
average_laptime = get_average_laptime(FP2)
stint = get_stint(FP2)
tyre = get_tyre_compound(FP2)
qualifying_time = get_qualifying_data(Qualify)
starting_position = get_starting_position(Qualify)
result = get_race_results(Result)

print("Data Extraction Done.")

fp1_best.set_index("Driver",inplace=True)
fp2_best.set_index("Driver",inplace=True)
fp3_best.set_index("Driver",inplace=True)
sector_time_best.set_index("Driver",inplace=True)
average_laptime.set_index("Driver",inplace=True)
stint.set_index("Driver",inplace=True)
tyre.set_index("Driver",inplace=True)
qualifying_time.set_index("Driver",inplace=True)
starting_position.set_index("Driver",inplace=True)
result.set_index("Driver",inplace=True)

print("Setting Index Done.")

df = fp1_best.copy()
df.rename(columns={"LapTime":"FP1_BestTime(s)"},inplace=True)
df[["FP2_BestTime(s)"]] = fp2_best[["LapTime"]]
df[["FP3_BestTime(s)"]] = fp3_best[["LapTime"]]
df[["Sector1Time(s)","Sector2Time(s)","Sector3Time(s)"]] = sector_time_best[["Sector1Time","Sector2Time","Sector3Time"]]
df[["Average_Laptime(s)"]] = average_laptime[["LapTime"]]
df[["Longest_Stint"]] = stint[["LongestStint"]]
df[["Tyre_Compound"]] = tyre[["Compound"]]
df[["Qualifying_Time(s)"]] = qualifying_time[["Qualifying_Time(s)"]]
df[["Starting_Pos"]] = starting_position[["Position"]]
df[["Race_Result"]] = result[["Position"]]

print("Data Transformation.")

fp1_best.reset_index(inplace=True)
fp2_best.reset_index(inplace=True)
fp3_best.reset_index(inplace=True)
sector_time_best.reset_index(inplace=True)
average_laptime.reset_index(inplace=True)
stint.reset_index(inplace=True)
tyre.reset_index(inplace=True)
qualifying_time.reset_index(inplace=True)
starting_position.reset_index(inplace=True)
result.reset_index(inplace=True)
df.reset_index(inplace=True)

print("Resetting Index Done.")

req         WARNING 	DEFAULT CACHE ENABLED! (12.29 GB) /home/satyam/.cache/fastf1

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 14
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 2 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 3 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 18
core        WARNING 	No lap data for driver 55
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '6', '16', '81', '1', '44', '30', '41', '5', '27', '87', '31', '10', '23', '43', '14', '11', '77', '18', '3', '55']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 81
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 81)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '16', '44', '1', '3', '87', '41', '5', '10', '31', '23', '30', '43', '55', '11', '18', '14', '77', '6', '81', '27']

Done Loading Season 2026 & Race Australia
Data Extraction Done.
Setting Index Done.
Data Transformation.
Resetting Index Done.

/tmp/ipykernel_13829/2861812837.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quali_results.rename(columns={"Abbreviation":"Driver"},inplace=True)
/tmp/ipykernel_13829/2097842272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [14]:
df

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result
0,ALB,83.130,81.847,81.664,36.650031,20.898312,42.942393,100.398929,11,HARD,80.941,15.0,12.0
1,ANT,81.376,79.943,80.324,36.042935,19.788161,41.798556,95.665077,15,HARD,78.811,2.0,2.0
2,BEA,82.682,81.326,80.778,39.039839,20.835774,41.873786,102.072750,15,HARD,80.311,12.0,7.0
3,BOR,81.696,81.668,80.459,39.209964,20.777286,46.708920,99.549182,9,MEDIUM,80.221,10.0,9.0
4,BOT,84.022,83.660,83.514,37.285821,20.556821,43.604600,101.500360,15,MEDIUM,83.244,19.0,19.0
5,COL,83.325,82.619,81.413,38.297846,22.258222,45.171583,101.418318,11,MEDIUM,81.270,16.0,14.0
6,GAS,84.035,82.167,81.071,37.261133,22.742125,41.458429,99.050308,11,MEDIUM,80.501,14.0,10.0
7,HAD,81.087,80.941,80.137,36.938357,23.917321,42.749958,99.028217,13,MEDIUM,79.303,3.0,20.0
8,HAM,80.736,80.050,79.669,36.481677,21.753969,43.648655,99.920000,13,HARD,79.478,7.0,4.0
9,HUL,81.969,81.351,81.067,34.139485,20.528765,41.426839,93.962483,10,MEDIUM,80.303,11.0,22.0
10,LAW,82.613,81.358,80.890,35.426966,21.766172,41.597720,97.647800,14,MEDIUM,79.994,8.0,13.0
11,LEC,80.267,80.291,79.827,37.004633,20.809667,45.400444,99.486360,10,HARD,79.327,4.0,3.0
12,LIN,81.313,80.922,80.838,39.199867,20.971933,43.092519,101.070296,15,SOFT,81.247,9.0,8.0
13,NOR,84.391,80.794,80.443,33.216286,20.360862,42.638692,92.236042,16,SOFT,79.475,6.0,5.0
14,OCO,82.161,81.179,80.983,39.771345,20.526621,45.612115,102.046375,10,HARD,80.491,13.0,11.0
15,PER,84.620,NaN,84.397,40.033500,21.311000,53.610000,118.806000,2,SOFT,82.605,18.0,16.0
16,PIA,81.342,79.729,80.087,36.638115,20.288808,43.384000,96.971182,10,HARD,79.380,5.0,21.0
17,RUS,81.371,80.049,79.053,38.616071,20.045714,42.000042,101.140833,13,HARD,78.518,1.0,1.0
18,SAI,82.323,82.253,NaN,35.224000,21.142100,44.954667,102.363111,7,MEDIUM,NaN,NaN,15.0
19,VER,80.789,80.366,80.197,37.872231,19.745000,41.107000,93.862300,5,MEDIUM,NaN,NaN,6.0

In [15]:
df.to_csv("AustraliaGP.csv",index=False)

# Japan GP Data (For Training)

In [16]:
season = 2026
race = 'Japan'

FP1 = fastf1.get_session(season, race, 'FP1')
FP1.load()
FP2 = fastf1.get_session(season, race, 'FP2')
FP2.load()
FP3 = fastf1.get_session(season, race, 'FP3')
FP3.load()

Qualify = fastf1.get_session(season, race, 'Q')
Qualify.load()

Result = fastf1.get_session(season, race, 'R')
Result.load()

print(f"Done Loading Season {season} & Race {race}")

fp1_best = get_fp1_best(FP1)
fp2_best = get_fp2_best(FP2)
fp3_best = get_fp3_best(FP3)
sector_time_best = get_sector_times(FP2)
average_laptime = get_average_laptime(FP2)
stint = get_stint(FP2)
tyre = get_tyre_compound(FP2)
qualifying_time = get_qualifying_data(Qualify)
starting_position = get_starting_position(Qualify)
result = get_race_results(Result)

print("Data Extraction Done.")

fp1_best.set_index("Driver",inplace=True)
fp2_best.set_index("Driver",inplace=True)
fp3_best.set_index("Driver",inplace=True)
sector_time_best.set_index("Driver",inplace=True)
average_laptime.set_index("Driver",inplace=True)
stint.set_index("Driver",inplace=True)
tyre.set_index("Driver",inplace=True)
qualifying_time.set_index("Driver",inplace=True)
starting_position.set_index("Driver",inplace=True)
result.set_index("Driver",inplace=True)

print("Setting Index Done.")

df = fp1_best.copy()
df.rename(columns={"LapTime":"FP1_BestTime(s)"},inplace=True)
df[["FP2_BestTime(s)"]] = fp2_best[["LapTime"]]
df[["FP3_BestTime(s)"]] = fp3_best[["LapTime"]]
df[["Sector1Time(s)","Sector2Time(s)","Sector3Time(s)"]] = sector_time_best[["Sector1Time","Sector2Time","Sector3Time"]]
df[["Average_Laptime(s)"]] = average_laptime[["LapTime"]]
df[["Longest_Stint"]] = stint[["LongestStint"]]
df[["Tyre_Compound"]] = tyre[["Compound"]]
df[["Qualifying_Time(s)"]] = qualifying_time[["Qualifying_Time(s)"]]
df[["Starting_Pos"]] = starting_position[["Position"]]
df[["Race_Result"]] = result[["Position"]]

print("Data Transformation.")

fp1_best.reset_index(inplace=True)
fp2_best.reset_index(inplace=True)
fp3_best.reset_index(inplace=True)
sector_time_best.reset_index(inplace=True)
average_laptime.reset_index(inplace=True)
stint.reset_index(inplace=True)
tyre.reset_index(inplace=True)
qualifying_time.reset_index(inplace=True)
starting_position.reset_index(inplace=True)
result.reset_index(inplace=True)
df.reset_index(inplace=True)

print("Resetting Index Done.")

core           INFO 	Loading data for Japanese Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '16', '18', '23', '27', '30', '31', '34', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Practice 2 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Practice 3 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 30: Lap timing integrity check failed for 1 lap(s)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '81', '16', '63', '1', '44', '10', '3', '30', '31', '27', '6', '5', '41', '55', '43', '11', '14', '77', '23', '18', '87']

Done Loading Season 2026 & Race Japan
Data Extraction Done.
Setting Index Done.
Data Transformation.
Resetting Index Done.

/tmp/ipykernel_13829/2861812837.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quali_results.rename(columns={"Abbreviation":"Driver"},inplace=True)
/tmp/ipykernel_13829/2097842272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [17]:
df

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result
0,ALB,93.697,91.496,91.733,42.531231,48.057667,21.567000,106.666583,11.0,MEDIUM,91.088,17.0,20.0
1,ANT,91.692,90.225,89.362,47.109174,45.386107,21.655821,103.388474,10.0,MEDIUM,88.778,1.0,1.0
2,BEA,92.900,91.498,91.558,43.953800,45.669714,22.014214,102.402952,15.0,MEDIUM,91.090,18.0,22.0
3,BOR,92.759,91.933,91.000,53.260667,48.081545,24.916545,119.585250,7.0,SOFT,90.274,9.0,13.0
4,BOT,94.490,92.615,92.503,43.989200,47.002679,21.424036,109.386375,15.0,MEDIUM,92.330,20.0,19.0
5,COL,93.361,92.438,91.759,43.006280,47.661536,21.347107,104.757091,14.0,MEDIUM,90.627,15.0,16.0
6,CRA,96.362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,GAS,92.978,91.734,91.082,41.008560,46.617310,21.627517,106.528667,13.0,HARD,89.691,7.0,7.0
8,HAD,92.803,91.759,91.094,45.154038,46.109931,21.571241,106.243957,14.0,HARD,89.978,8.0,12.0
9,HAM,92.040,90.980,90.383,46.753333,49.164185,22.050000,104.465000,9.0,MEDIUM,89.567,6.0,6.0
10,HUL,92.798,91.441,90.658,42.662375,45.554074,22.005074,104.905045,8.0,HARD,90.387,13.0,11.0
11,LAW,92.529,91.590,91.097,42.420000,47.320533,21.645833,107.318542,14.0,MEDIUM,90.495,14.0,9.0
12,LEC,91.955,90.846,90.229,43.150960,46.994536,22.093107,107.622043,12.0,MEDIUM,89.405,4.0,3.0
13,LIN,92.665,NaN,91.288,NaN,69.262000,38.967000,NaN,1.0,MEDIUM,90.319,10.0,14.0
14,NOR,91.798,90.649,90.600,45.334286,46.782176,24.024941,108.705583,9.0,SOFT,89.409,5.0,5.0
15,OCO,92.601,91.532,91.326,43.407370,46.763433,21.440467,104.676208,15.0,MEDIUM,90.309,12.0,10.0
16,PER,94.221,93.689,92.540,47.314417,45.573786,22.538429,106.543600,9.0,HARD,92.206,19.0,17.0
17,PIA,91.865,90.133,90.364,42.560769,45.652448,21.447586,105.411958,10.0,MEDIUM,89.132,3.0,2.0
18,RUS,91.666,90.338,89.616,47.393800,45.788276,22.059000,107.931045,9.0,MEDIUM,89.076,2.0,4.0
19,SAI,93.383,91.608,91.829,42.486538,46.049067,20.790467,105.217167,12.0,HARD,91.033,16.0,15.0
20,STR,95.294,93.951,93.485,44.378000,47.618476,21.998000,114.290000,7.0,SOFT,92.920,22.0,21.0
21,VER,92.457,91.509,90.910,43.427846,44.212276,21.476103,103.802417,18.0,HARD,90.262,11.0,8.0

In [18]:
df.to_csv("JapanGP.csv",index=False)

# China GP Data (For Training)

In [19]:
season = 2026
race = 'China'

FP1 = fastf1.get_session(season, race, 'FP1')
FP1.load()
FP2 = fastf1.get_session(season, race, 'SQ')
FP2.load()
FP3 = fastf1.get_session(season, race, 'S')
FP3.load()

Qualify = fastf1.get_session(season, race, 'Q')
Qualify.load()

Result = fastf1.get_session(season, race, 'R')
Result.load()

print(f"Done Loading Season {season} & Race {race}")

fp1_best = get_fp1_best(FP1)
fp2_best = get_fp2_best(FP2)
fp3_best = get_fp3_best(FP3)
sector_time_best = get_sector_times(FP2)
average_laptime = get_average_laptime(FP2)
stint = get_stint(FP2)
tyre = get_tyre_compound(FP2)
qualifying_time = get_qualifying_data(Qualify)
starting_position = get_starting_position(Qualify)
result = get_race_results(Result)

print("Data Extraction Done.")

fp1_best.set_index("Driver",inplace=True)
fp2_best.set_index("Driver",inplace=True)
fp3_best.set_index("Driver",inplace=True)
sector_time_best.set_index("Driver",inplace=True)
average_laptime.set_index("Driver",inplace=True)
stint.set_index("Driver",inplace=True)
tyre.set_index("Driver",inplace=True)
qualifying_time.set_index("Driver",inplace=True)
starting_position.set_index("Driver",inplace=True)
result.set_index("Driver",inplace=True)

print("Setting Index Done.")

df = fp1_best.copy()
df.rename(columns={"LapTime":"FP1_BestTime(s)"},inplace=True)
df[["FP2_BestTime(s)"]] = fp2_best[["LapTime"]]
df[["FP3_BestTime(s)"]] = fp3_best[["LapTime"]]
df[["Sector1Time(s)","Sector2Time(s)","Sector3Time(s)"]] = sector_time_best[["Sector1Time","Sector2Time","Sector3Time"]]
df[["Average_Laptime(s)"]] = average_laptime[["LapTime"]]
df[["Longest_Stint"]] = stint[["LongestStint"]]
df[["Tyre_Compound"]] = tyre[["Compound"]]
df[["Qualifying_Time(s)"]] = qualifying_time[["Qualifying_Time(s)"]]
df[["Starting_Pos"]] = starting_position[["Position"]]
df[["Race_Result"]] = result[["Position"]]

print("Data Transformation.")

fp1_best.reset_index(inplace=True)
fp2_best.reset_index(inplace=True)
fp3_best.reset_index(inplace=True)
sector_time_best.reset_index(inplace=True)
average_laptime.reset_index(inplace=True)
stint.reset_index(inplace=True)
tyre.reset_index(inplace=True)
qualifying_time.reset_index(inplace=True)
starting_position.reset_index(inplace=True)
result.reset_index(inplace=True)
df.reset_index(inplace=True)

print("Resetting Index Done.")

core           INFO 	Loading data for Chinese Grand Prix - Practice 1 [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Chinese Grand Prix - Sprint Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 11
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 11)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['63', '12', '1', '44', '81', '16', '10', '3', '87', '6', '27', '31', '30', '5', '41', '43', '55', '23', '14', '18', '77', '11']
core           INFO 	Loading data for Chinese Grand Prix - Sprint [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 63 completed the race distance 00:00.009000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['63', '16', '44', '1', '12', '81', '30', '87', '3', '31', '10', '55', '5', '43', '6', '23', '14', '18', '11', '27', '77', '41']
core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '81', '1', '10', '3', '6', '87', '27', '43', '31', '30', '41', '5', '55', '23', '14', '77', '18', '11']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 12 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '87', '10', '30', '6', '55', '43', '27', '41', '77', '31', '11', '3', '14', '18', '81', '1', '5', '23']

Done Loading Season 2026 & Race China
Data Extraction Done.
Setting Index Done.
Data Transformation.
Resetting Index Done.

/tmp/ipykernel_13829/2861812837.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quali_results.rename(columns={"Abbreviation":"Driver"},inplace=True)
/tmp/ipykernel_13829/2097842272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [20]:
df

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result
0,ALB,95.480,95.305,98.158,27.300600,31.527667,49.645000,108.962200,6.0,MEDIUM,94.772,18.0,22.0
1,ALO,95.856,95.581,98.487,28.490000,31.746600,48.075000,107.564250,5.0,MEDIUM,95.203,19.0,17.0
2,ANT,92.861,91.809,94.760,28.116400,32.863769,47.599231,107.658700,5.0,MEDIUM,92.064,1.0,1.0
3,BEA,94.426,93.409,97.374,29.538154,31.894063,48.543625,110.244462,7.0,MEDIUM,93.292,10.0,5.0
4,BOR,94.828,93.774,97.800,28.943000,32.736714,48.478214,110.359250,8.0,MEDIUM,93.965,16.0,21.0
5,BOT,96.057,97.378,99.262,28.484571,33.107250,48.428500,109.943714,8.0,MEDIUM,95.436,20.0,13.0
6,COL,94.947,94.327,97.278,30.291600,33.194917,47.793000,111.528000,6.0,MEDIUM,93.357,12.0,10.0
7,GAS,94.676,92.888,98.349,29.145417,32.768933,49.672133,112.275500,6.0,MEDIUM,92.873,7.0,6.0
8,HAD,94.856,93.620,96.912,30.018583,31.808333,47.518714,107.512636,7.0,MEDIUM,93.121,9.0,8.0
9,HAM,94.129,92.161,94.926,28.891417,33.737000,49.144600,111.767250,5.0,MEDIUM,92.415,3.0,3.0
10,HUL,94.639,93.635,98.027,28.202083,33.229071,46.597000,107.721083,8.0,MEDIUM,93.354,11.0,11.0
11,LAW,94.773,93.714,97.882,27.259545,32.162615,48.857077,108.130000,7.0,MEDIUM,93.765,14.0,7.0
12,LEC,93.599,92.528,94.753,28.035833,31.963625,49.602250,108.046917,7.0,MEDIUM,92.428,4.0,4.0
13,LIN,97.896,94.048,98.475,27.856364,31.910154,48.277077,108.096091,7.0,MEDIUM,93.784,15.0,12.0
14,NOR,93.296,92.141,95.708,27.693500,31.314462,49.217769,108.887100,6.0,MEDIUM,92.608,6.0,20.0
15,OCO,94.877,93.639,97.363,27.888000,32.825308,49.634769,110.530091,7.0,MEDIUM,93.538,13.0,14.0
16,PER,99.200,NaN,98.862,NaN,NaN,NaN,NaN,NaN,NaN,96.906,22.0,15.0
17,PIA,93.472,92.224,95.635,28.373100,32.226769,48.985538,110.358700,6.0,MEDIUM,92.550,5.0,19.0
18,RUS,92.741,91.520,95.101,27.978700,32.987769,49.256538,109.650000,5.0,MEDIUM,92.286,2.0,2.0
19,SAI,95.679,94.761,97.913,29.112000,32.322000,48.965000,110.994200,6.0,MEDIUM,94.317,17.0,9.0
20,STR,97.224,96.151,98.532,29.756167,33.753429,49.822143,113.359500,7.0,MEDIUM,95.995,21.0,18.0
21,VER,94.541,93.254,95.774,29.153714,32.952235,47.594059,109.184500,7.0,MEDIUM,93.002,8.0,16.0

In [21]:
df.to_csv("ChinaGP.csv",index=False)

# Miami GP (For Prediction)

In [22]:
season = 2026
race = 'Miami'

FP1 = fastf1.get_session(season, race, 'FP1')
FP1.load()
FP2 = fastf1.get_session(season, race, 'SQ')
FP2.load()
FP3 = fastf1.get_session(season, race, 'S')
FP3.load()

Qualify = fastf1.get_session(season, race, 'Q')
Qualify.load()


print(f"Done Loading Season {season} & Race {race}")

fp1_best = get_fp1_best(FP1)
fp2_best = get_fp2_best(FP2)
fp3_best = get_fp3_best(FP3)
sector_time_best = get_sector_times(FP2)
average_laptime = get_average_laptime(FP2)
stint = get_stint(FP2)
tyre = get_tyre_compound(FP2)
qualifying_time = get_qualifying_data(Qualify)
starting_position = get_starting_position(Qualify)

print("Data Extraction Done.")

fp1_best.set_index("Driver",inplace=True)
fp2_best.set_index("Driver",inplace=True)
fp3_best.set_index("Driver",inplace=True)
sector_time_best.set_index("Driver",inplace=True)
average_laptime.set_index("Driver",inplace=True)
stint.set_index("Driver",inplace=True)
tyre.set_index("Driver",inplace=True)
qualifying_time.set_index("Driver",inplace=True)
starting_position.set_index("Driver",inplace=True)
print("Setting Index Done.")

df = fp1_best.copy()
df.rename(columns={"LapTime":"FP1_BestTime(s)"},inplace=True)
df[["FP2_BestTime(s)"]] = fp2_best[["LapTime"]]
df[["FP3_BestTime(s)"]] = fp3_best[["LapTime"]]
df[["Sector1Time(s)","Sector2Time(s)","Sector3Time(s)"]] = sector_time_best[["Sector1Time","Sector2Time","Sector3Time"]]
df[["Average_Laptime(s)"]] = average_laptime[["LapTime"]]
df[["Longest_Stint"]] = stint[["LongestStint"]]
df[["Tyre_Compound"]] = tyre[["Compound"]]
df[["Qualifying_Time(s)"]] = qualifying_time[["Qualifying_Time(s)"]]
df[["Starting_Pos"]] = starting_position[["Position"]]

print("Data Transformation.")

fp1_best.reset_index(inplace=True)
fp2_best.reset_index(inplace=True)
fp3_best.reset_index(inplace=True)
sector_time_best.reset_index(inplace=True)
average_laptime.reset_index(inplace=True)
stint.reset_index(inplace=True)
tyre.reset_index(inplace=True)
qualifying_time.reset_index(inplace=True)
starting_position.reset_index(inplace=True)
df.reset_index(inplace=True)

print("Resetting Index Done.")

core           INFO 	Loading data for Miami Grand Prix - Practice 1 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver 81: Encountered 1 timing integrity error(s) near lap(s): [35].
This might be a bug and should be reported.
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Miami Grand Prix - Sprint Qualifying [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
core        WARNING 	Sprint Qualifying is not supported by Ergast! Limited results are calculated from timing data.
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '12', '81', '16', '3', '63', '44', '43', '6', '10', '5', '27', '87', '23', '55', '41', '30', '31', '11', '77', '14', '18']
core           INFO 	Loading data for Miami Grand Prix - Sprint [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '81', '16', '63', '3', '12', '44', '10', '6', '43', '31', '87', '55', '30', '14', '11', '18', '23', '77', '27', '41', '5']
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
_api        WARNING 	Driver 81: Encountered 1 timing integrity error(s) near lap(s): [3].
This might be a bug and should be reported.
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '3', '16', '1', '63', '44', '81', '43', '6', '10', '27', '30', '87', '55', '31', '23', '41', '14', '18', '77', '11', '5']

Done Loading Season 2026 & Race Miami
Data Extraction Done.
Setting Index Done.
Data Transformation.
Resetting Index Done.

/tmp/ipykernel_13829/2861812837.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  quali_results.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [23]:
df

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos
0,ALB,91.024,90.216,93.473,40.930200,40.687333,31.818667,112.258500,6,MEDIUM,89.946,16.0
1,ALO,92.593,92.490,94.720,37.105200,39.793167,34.718667,111.428600,6,MEDIUM,91.098,18.0
2,ANT,90.079,88.091,91.932,39.886700,40.724857,33.187923,106.295500,3,MEDIUM,87.798,1.0
3,BEA,91.091,90.116,94.524,40.357000,39.887444,31.671333,110.144833,3,MEDIUM,89.567,13.0
4,BOR,91.111,89.994,94.174,37.460000,41.726500,33.908167,111.922889,6,MEDIUM,93.737,22.0
5,BOT,92.762,91.826,95.856,36.451500,40.314667,36.732800,92.071500,3,MEDIUM,91.629,20.0
6,COL,91.015,89.320,93.139,39.173833,39.762400,31.374500,109.832000,6,MEDIUM,88.762,8.0
7,GAS,90.587,89.474,93.072,39.254417,40.081667,30.743786,109.097636,6,MEDIUM,88.810,10.0
8,HAD,90.873,89.422,93.119,36.692083,40.412400,31.293143,106.426636,6,MEDIUM,88.789,9.0
9,HAM,89.777,88.618,92.448,38.031750,39.298200,30.978429,107.213273,6,MEDIUM,88.319,6.0
10,HUL,91.595,90.019,NaN,36.696111,39.646000,35.762417,111.277667,6,MEDIUM,89.439,11.0
11,LAW,91.648,91.043,94.204,35.239000,41.875400,33.851400,108.776667,3,MEDIUM,89.499,12.0
12,LEC,89.310,88.239,91.964,37.248333,40.522133,30.256286,107.127000,6,MEDIUM,88.143,3.0
13,LIN,92.862,90.573,NaN,35.695833,39.129333,37.534111,112.617000,3,MEDIUM,90.133,17.0
14,NOR,90.208,87.869,91.885,36.548167,40.037467,32.785571,108.265727,7,MEDIUM,88.183,4.0
15,OCO,91.635,91.245,94.409,37.663500,40.661667,31.575000,108.342250,3,MEDIUM,89.772,15.0
16,PER,92.047,91.255,95.015,36.188500,40.089333,42.648333,122.447500,3,MEDIUM,91.967,21.0
17,PIA,89.758,88.108,92.079,39.577889,40.305273,33.269778,111.682429,5,MEDIUM,88.500,7.0
18,RUS,90.100,88.493,92.387,39.324091,40.503000,34.202357,106.589556,3,MEDIUM,88.197,5.0
19,SAI,90.930,90.224,94.008,39.058700,41.538333,31.354167,111.177600,6,MEDIUM,89.568,14.0
20,STR,92.959,NaN,95.009,37.744000,39.904000,43.944667,125.395000,3,MEDIUM,91.164,19.0
21,VER,89.607,88.461,92.201,37.386556,39.817500,30.584364,105.282000,6,MEDIUM,87.964,2.0

In [24]:
df.to_csv("MiamiGP.csv",index=False)