In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import fastf1
import requests
from scipy.stats import spearmanr

In [2]:
def get_race_results(Result):

    race = Result.results[["Abbreviation","Position"]]
    race.rename(columns={"Abbreviation":"Driver"},inplace=True)

    return race

In [3]:
season = 2026
race = 'Miami'

Result = fastf1.get_session(season, race, 'R')
Result.load()


result = get_race_results(Result)

req         WARNING 	DEFAULT CACHE ENABLED! (12.6 GB) /home/satyam/.cache/fastf1
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.1]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 12 completed the race distance 00:00.027000 before the recorded end of the session.
core           INFO 	Finished loading data for 22 drivers: ['12', '1', '81', '63', '3', '44', '43', '16', '55', '23', '87', '5', '31', '41', '14', '11', '18', '77', '27', '30', '10', '6']
/tmp/ipykernel_42997/2097842272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [4]:
result

   Driver  Position
12    ANT       1.0
1     NOR       2.0
81    PIA       3.0
63    RUS       4.0
3     VER       5.0
44    HAM       6.0
43    COL       7.0
16    LEC       8.0
55    SAI       9.0
23    ALB      10.0
87    BEA      11.0
5     BOR      12.0
31    OCO      13.0
41    LIN      14.0
14    ALO      15.0
11    PER      16.0
18    STR      17.0
77    BOT      18.0
27    HUL      19.0
30    LAW      20.0
10    GAS      21.0
6     HAD      22.0

In [5]:
result.reset_index(inplace=True, drop=True)

In [6]:
result

   Driver  Position
0     ANT       1.0
1     NOR       2.0
2     PIA       3.0
3     RUS       4.0
4     VER       5.0
5     HAM       6.0
6     COL       7.0
7     LEC       8.0
8     SAI       9.0
9     ALB      10.0
10    BEA      11.0
11    BOR      12.0
12    OCO      13.0
13    LIN      14.0
14    ALO      15.0
15    PER      16.0
16    STR      17.0
17    BOT      18.0
18    HUL      19.0
19    LAW      20.0
20    GAS      21.0
21    HAD      22.0

In [7]:
PRE = pd.read_csv("Data/Predicted_Results.csv")

In [8]:
PRE

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos,Predicted,Predicted_Pos
0,ANT,90.079,88.091,91.932,106.295500,87.798,1.0,1.968844,1
1,VER,89.607,88.461,92.201,105.282000,87.964,2.0,2.538575,2
2,NOR,90.208,87.869,91.885,108.265727,88.183,4.0,4.030899,3
3,LEC,89.310,88.239,91.964,107.127000,88.143,3.0,4.128328,4
4,HAM,89.777,88.618,92.448,107.213273,88.319,6.0,9.154425,5
5,PIA,89.758,88.108,92.079,111.682429,88.500,7.0,9.400062,6
6,RUS,90.100,88.493,92.387,106.589556,88.197,5.0,10.199090,7
7,LAW,91.648,91.043,94.204,108.776667,89.499,12.0,10.214101,8
8,HAD,90.873,89.422,93.119,106.426636,88.789,9.0,10.292932,9
9,SAI,90.930,90.224,94.008,111.177600,89.568,14.0,10.791463,10
10,HUL,91.595,90.019,93.306,111.277667,89.439,11.0,10.791463,11
11,BEA,91.091,90.116,94.524,110.144833,89.567,13.0,10.791463,12
12,GAS,90.587,89.474,93.072,109.097636,88.810,10.0,10.870295,13
13,COL,91.015,89.320,93.139,109.832000,88.762,8.0,10.870295,14
14,OCO,91.635,91.245,94.409,108.342250,89.772,15.0,12.151595,15
15,ALB,91.024,90.216,93.473,112.258500,89.946,16.0,15.936033,16
16,LIN,92.862,90.573,93.306,112.617000,90.133,17.0,16.411399,17
17,PER,92.047,91.255,95.015,122.447500,91.967,21.0,18.318462,18
18,STR,92.959,89.994,95.009,125.395000,91.164,19.0,18.318462,19
19,ALO,92.593,92.490,94.720,111.428600,91.098,18.0,18.444857,20
20,BOT,92.762,91.826,95.856,92.071500,91.629,20.0,18.566632,21
21,BOR,91.111,89.994,94.174,111.922889,93.737,22.0,18.573085,22

In [ ]:
PRE.set_index("Driver", inplace=True)
result.set_index("Driver", inplace=True)

Final = result.copy()
Final["Predicted_Pos"] = PRE["Predicted_Pos"]

PRE.reset_index(inplace=True)
Final.reset_index(inplace=True)
result.reset_index(inplace=True)

In [10]:
Final

   Driver  Position  Predicted_Pos
0     ANT       1.0              1
1     NOR       2.0              3
2     PIA       3.0              6
3     RUS       4.0              7
4     VER       5.0              2
5     HAM       6.0              5
6     COL       7.0             14
7     LEC       8.0              4
8     SAI       9.0             10
9     ALB      10.0             16
10    BEA      11.0             12
11    BOR      12.0             22
12    OCO      13.0             15
13    LIN      14.0             17
14    ALO      15.0             20
15    PER      16.0             18
16    STR      17.0             19
17    BOT      18.0             21
18    HUL      19.0             11
19    LAW      20.0              8
20    GAS      21.0             13
21    HAD      22.0              9

In [11]:

rho, p_value = spearmanr(Final['Position'],Final['Predicted_Pos'])

In [12]:
print(f"{rho}, {p_value}")

0.5889328063241107, 0.0039297192541944736

In [13]:
podium = Final.loc[:,["Driver"]]
print("\n Final Standing")
print(f"🥇P1: {podium.iloc[0]['Driver']}")
print(f"🥈P2: {podium.iloc[1]['Driver']}")
print(f"🥉P3: {podium.iloc[2]['Driver']}")
print(f"P4: {podium.iloc[3]['Driver']}")
print(f"P5: {podium.iloc[4]['Driver']}")
print(f"P6: {podium.iloc[5]['Driver']}")
print(f"P7: {podium.iloc[6]['Driver']}")
print(f"P8: {podium.iloc[7]['Driver']}")
print(f"P9: {podium.iloc[8]['Driver']}")
print(f"P10: {podium.iloc[9]['Driver']}")
print(f"P11: {podium.iloc[10]['Driver']}")
print(f"P12: {podium.iloc[11]['Driver']}")

print(f"Spearman Rank (Final): {rho:.2f}")

 Final Standing
🥇P1: ANT
🥈P2: NOR
🥉P3: PIA
P4: RUS
P5: VER
P6: HAM
P7: COL
P8: LEC
P9: SAI
P10: ALB
P11: BEA
P12: BOR
Spearman Rank (Final): 0.59

In [14]:
PRE

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos,Predicted,Predicted_Pos
0,ANT,90.079,88.091,91.932,106.295500,87.798,1.0,1.968844,1
1,VER,89.607,88.461,92.201,105.282000,87.964,2.0,2.538575,2
2,NOR,90.208,87.869,91.885,108.265727,88.183,4.0,4.030899,3
3,LEC,89.310,88.239,91.964,107.127000,88.143,3.0,4.128328,4
4,HAM,89.777,88.618,92.448,107.213273,88.319,6.0,9.154425,5
5,PIA,89.758,88.108,92.079,111.682429,88.500,7.0,9.400062,6
6,RUS,90.100,88.493,92.387,106.589556,88.197,5.0,10.199090,7
7,LAW,91.648,91.043,94.204,108.776667,89.499,12.0,10.214101,8
8,HAD,90.873,89.422,93.119,106.426636,88.789,9.0,10.292932,9
9,SAI,90.930,90.224,94.008,111.177600,89.568,14.0,10.791463,10
10,HUL,91.595,90.019,93.306,111.277667,89.439,11.0,10.791463,11
11,BEA,91.091,90.116,94.524,110.144833,89.567,13.0,10.791463,12
12,GAS,90.587,89.474,93.072,109.097636,88.810,10.0,10.870295,13
13,COL,91.015,89.320,93.139,109.832000,88.762,8.0,10.870295,14
14,OCO,91.635,91.245,94.409,108.342250,89.772,15.0,12.151595,15
15,ALB,91.024,90.216,93.473,112.258500,89.946,16.0,15.936033,16
16,LIN,92.862,90.573,93.306,112.617000,90.133,17.0,16.411399,17
17,PER,92.047,91.255,95.015,122.447500,91.967,21.0,18.318462,18
18,STR,92.959,89.994,95.009,125.395000,91.164,19.0,18.318462,19
19,ALO,92.593,92.490,94.720,111.428600,91.098,18.0,18.444857,20
20,BOT,92.762,91.826,95.856,92.071500,91.629,20.0,18.566632,21
21,BOR,91.111,89.994,94.174,111.922889,93.737,22.0,18.573085,22

In [16]:
result

        Position
Driver
ANT          1.0
NOR          2.0
PIA          3.0
RUS          4.0
VER          5.0
HAM          6.0
COL          7.0
LEC          8.0
SAI          9.0
ALB         10.0
BEA         11.0
BOR         12.0
OCO         13.0
LIN         14.0
ALO         15.0
PER         16.0
STR         17.0
BOT         18.0
HUL         19.0
LAW         20.0
GAS         21.0
HAD         22.0

In [15]:
PRE.set_index("Driver", inplace=True)
result.set_index("Driver", inplace=True)

df = PRE.copy()
df["Actual_Pos"] = result["Position"]


PRE.reset_index(inplace=True)
Final.reset_index(inplace=True)

KeyError: "None of ['Driver'] are in the columns"