In [6]:
import pandas as pd

In [7]:
CAN = pd.read_csv('Data/CanadaGP.csv')

In [8]:
CAN

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),Sector3Time(s),Average_Laptime(s),Longest_Stint,Tyre_Compound,Qualifying_Time(s),Starting_Pos,Race_Result
0,ALB,76.642,NaN,75.717,NaN,NaN,NaN,NaN,NaN,NaN,74.851,18.0,NaN
1,ALO,75.863,75.760,77.543,27.015429,27.536667,36.476000,91.071500,7.0,MEDIUM,75.196,19.0,NaN
2,ANT,73.402,73.033,74.380,24.462867,27.006937,36.096462,88.209083,6.0,MEDIUM,72.646,2.0,NaN
3,BEA,77.770,75.197,76.210,26.360750,26.780059,35.207714,89.245077,8.0,MEDIUM,74.416,16.0,NaN
4,BOR,76.214,74.627,75.980,27.324714,28.032857,35.385909,89.142545,7.0,MEDIUM,74.071,13.0,NaN
5,BOT,77.868,76.866,77.212,26.833125,27.350500,34.621167,88.958000,7.0,MEDIUM,76.272,22.0,NaN
6,GAS,76.809,76.642,76.150,26.236000,26.903429,34.603500,87.290667,6.0,MEDIUM,74.187,14.0,NaN
7,HAD,76.253,73.605,74.941,26.351125,27.535937,35.148071,88.088857,6.0,MEDIUM,72.935,7.0,NaN
8,HAM,74.176,73.326,74.695,24.798429,27.069591,33.615579,85.331389,8.0,MEDIUM,72.868,5.0,NaN
9,HUL,75.698,74.595,76.297,26.850500,27.492286,34.247273,86.996182,7.0,MEDIUM,73.886,11.0,NaN
10,LAW,77.431,NaN,76.257,NaN,NaN,NaN,NaN,NaN,NaN,73.897,12.0,NaN
11,LEC,74.355,73.410,74.741,25.318526,27.003000,35.880250,88.173125,7.0,MEDIUM,72.976,8.0,NaN
12,LIN,75.452,73.737,75.653,25.524526,27.817444,35.682250,88.946625,7.0,MEDIUM,73.280,9.0,NaN
13,NOR,74.799,73.280,74.596,25.347000,26.387267,37.436917,89.301583,7.0,MEDIUM,72.729,3.0,NaN
14,OCO,76.497,74.928,76.849,26.097176,26.851500,35.798571,88.805429,8.0,MEDIUM,74.845,17.0,NaN
15,PER,77.926,76.002,76.641,25.216125,27.253857,33.536833,84.744000,7.0,MEDIUM,75.429,20.0,NaN
16,PIA,74.963,73.299,74.793,27.788600,27.393933,37.005167,91.068583,6.0,MEDIUM,72.781,4.0,NaN
17,RUS,73.544,72.965,74.702,24.087889,26.450421,36.526353,87.752375,7.0,MEDIUM,72.578,1.0,NaN
18,SAI,76.660,74.536,75.943,26.809000,27.738625,34.576850,87.875158,8.0,MEDIUM,74.273,15.0,NaN
19,STR,76.978,76.354,77.120,26.713857,27.152500,36.901429,91.682000,7.0,MEDIUM,76.195,21.0,NaN
20,VER,74.366,73.504,74.974,25.239286,26.922500,34.624667,85.870167,6.0,MEDIUM,72.907,6.0,NaN

In [9]:
CAN.drop(['Race_Result','Tyre_Compound','Sector1Time(s)','Sector2Time(s)','Sector3Time(s)','Longest_Stint'], axis=1,inplace=True)

In [10]:
CAN

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos
0,ALB,76.642,NaN,75.717,NaN,74.851,18.0
1,ALO,75.863,75.760,77.543,91.071500,75.196,19.0
2,ANT,73.402,73.033,74.380,88.209083,72.646,2.0
3,BEA,77.770,75.197,76.210,89.245077,74.416,16.0
4,BOR,76.214,74.627,75.980,89.142545,74.071,13.0
5,BOT,77.868,76.866,77.212,88.958000,76.272,22.0
6,GAS,76.809,76.642,76.150,87.290667,74.187,14.0
7,HAD,76.253,73.605,74.941,88.088857,72.935,7.0
8,HAM,74.176,73.326,74.695,85.331389,72.868,5.0
9,HUL,75.698,74.595,76.297,86.996182,73.886,11.0
10,LAW,77.431,NaN,76.257,NaN,73.897,12.0
11,LEC,74.355,73.410,74.741,88.173125,72.976,8.0
12,LIN,75.452,73.737,75.653,88.946625,73.280,9.0
13,NOR,74.799,73.280,74.596,89.301583,72.729,3.0
14,OCO,76.497,74.928,76.849,88.805429,74.845,17.0
15,PER,77.926,76.002,76.641,84.744000,75.429,20.0
16,PIA,74.963,73.299,74.793,91.068583,72.781,4.0
17,RUS,73.544,72.965,74.702,87.752375,72.578,1.0
18,SAI,76.660,74.536,75.943,87.875158,74.273,15.0
19,STR,76.978,76.354,77.120,91.682000,76.195,21.0
20,VER,74.366,73.504,74.974,85.870167,72.907,6.0

In [11]:
CAN['FP2_BestTime(s)'].fillna(CAN['FP2_BestTime(s)'].median(),inplace=True)
CAN['Average_Laptime(s)'].fillna(CAN['Average_Laptime(s)'].mean(),inplace=True)

/tmp/ipykernel_403840/3506360672.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  CAN['FP2_BestTime(s)'].fillna(CAN['FP2_BestTime(s)'].median(),inplace=True)
/tmp/ipykernel_403840/3506360672.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  CAN['Average_Laptime(s)'].fillna(CAN['Average_Laptime(s)'].mean(),inplace=True)

In [12]:
CAN

,Driver,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Average_Laptime(s),Qualifying_Time(s),Starting_Pos
0,ALB,76.642,74.536,75.717,88.344860,74.851,18.0
1,ALO,75.863,75.760,77.543,91.071500,75.196,19.0
2,ANT,73.402,73.033,74.380,88.209083,72.646,2.0
3,BEA,77.770,75.197,76.210,89.245077,74.416,16.0
4,BOR,76.214,74.627,75.980,89.142545,74.071,13.0
5,BOT,77.868,76.866,77.212,88.958000,76.272,22.0
6,GAS,76.809,76.642,76.150,87.290667,74.187,14.0
7,HAD,76.253,73.605,74.941,88.088857,72.935,7.0
8,HAM,74.176,73.326,74.695,85.331389,72.868,5.0
9,HUL,75.698,74.595,76.297,86.996182,73.886,11.0
10,LAW,77.431,74.536,76.257,88.344860,73.897,12.0
11,LEC,74.355,73.410,74.741,88.173125,72.976,8.0
12,LIN,75.452,73.737,75.653,88.946625,73.280,9.0
13,NOR,74.799,73.280,74.596,89.301583,72.729,3.0
14,OCO,76.497,74.928,76.849,88.805429,74.845,17.0
15,PER,77.926,76.002,76.641,84.744000,75.429,20.0
16,PIA,74.963,73.299,74.793,91.068583,72.781,4.0
17,RUS,73.544,72.965,74.702,87.752375,72.578,1.0
18,SAI,76.660,74.536,75.943,87.875158,74.273,15.0
19,STR,76.978,76.354,77.120,91.682000,76.195,21.0
20,VER,74.366,73.504,74.974,85.870167,72.907,6.0