In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import fastf1
import requests
from scipy.stats import spearmanr

In [2]:
def get_race_results(Result):

    race = Result.results[["Abbreviation","Position"]]
    race.rename(columns={"Abbreviation":"Driver"},inplace=True)

    return race

In [3]:
season = 2026
race = 'Monaco'

Result = fastf1.get_session(season, race, 'R')
Result.load()


result = get_race_results(Result)

req         WARNING 	DEFAULT CACHE ENABLED! (13.12 GB) /home/satyam/.cache/fastf1
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '44', '6', '81', '30', '41', '10', '23', '31', '14', '5', '63', '27', '43', '11', '55', '16', '18', '1', '87', '77', '3']
/tmp/ipykernel_7944/2097842272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  race.rename(columns={"Abbreviation":"Driver"},inplace=True)

In [4]:
result.reset_index(inplace=True, drop=True)

In [5]:
result

   Driver  Position
0     ANT       1.0
1     HAM       2.0
2     HAD       3.0
3     PIA       4.0
4     LAW       5.0
5     LIN       6.0
6     GAS       7.0
7     ALB       8.0
8     OCO       9.0
9     ALO      10.0
10    BOR      11.0
11    RUS      12.0
12    HUL      13.0
13    COL      14.0
14    PER      15.0
15    SAI      16.0
16    LEC      17.0
17    STR      18.0
18    NOR      19.0
19    BEA      20.0
20    BOT      21.0
21    VER      22.0

In [6]:
PRE = pd.read_csv("Data/PredictedData.csv")
PRE

,Driver,Constructor,AveragePositionFromLast3Races,AveragePointsFromLast3Races,ConstructorAveragePointFromLast3Races,FP1_BestTime(s),FP2_BestTime(s),FP3_BestTime(s),Sector1Time(s),Sector2Time(s),...,Sector3_Rank,CombinedSectorTime,CombinedSectorDelta,LapTime_Rank,DeltaToFastestLap,StartXConst,DriXConst,FP3XStart,Predicted_Result,Predicted_Pos
0,ANT,Mercedes,9.000000,17.000000,31.0,74.537,73.529,72.720,23.736771,42.723088,...,17,93.315118,7.824569,19,6.691904,219.0,28689.0,1.0,4.686387,1
1,LEC,Ferrari,8.000000,6.000000,21.0,73.978,73.137,73.047,23.069171,41.336171,...,11,90.121062,4.630513,14,5.881308,588.0,11025.0,8.0,4.759162,2
2,HAM,Ferrari,8.666667,8.333333,21.0,74.204,73.026,73.051,24.465500,41.936057,...,18,93.499432,8.008884,21,8.259933,441.0,10584.0,9.0,4.847397,3
3,RUS,Mercedes,7.666667,9.833333,31.0,74.983,73.405,73.483,23.428030,42.588500,...,6,90.983917,5.493369,9,4.352733,1314.0,19272.0,24.0,6.348409,4
4,VER,Red Bull Racing,7.666667,8.833333,17.5,74.491,73.194,73.662,21.880200,38.904800,...,3,85.490548,0.000000,1,0.000000,114.0,2451.0,10.0,7.538481,5
5,PIA,McLaren,4.666667,9.833333,16.5,75.565,74.088,73.698,23.133323,40.818367,...,21,91.649578,6.159030,16,6.427093,742.0,5088.0,42.0,8.450545,6
6,NOR,McLaren,6.666667,12.333333,16.5,75.291,75.274,74.006,23.993625,41.239429,...,22,93.829768,8.339219,22,9.792442,848.0,6148.0,72.0,9.188462,7
7,HAD,Red Bull Racing,12.333333,6.166667,17.5,76.148,74.087,73.877,23.117913,40.684348,...,19,91.060629,5.570081,18,6.488503,285.0,798.0,40.0,9.212705,8
8,GAS,Alpine,11.000000,5.500000,9.0,75.828,74.497,74.480,24.386378,39.974889,...,4,89.212176,3.721628,6,3.805750,315.0,700.0,117.0,9.454453,9
9,LAW,Racing Bulls,11.000000,5.500000,3.0,76.431,74.785,74.587,22.825971,41.609743,...,12,90.369214,4.878666,13,5.818308,210.0,336.0,150.0,10.901116,10
10,SAI,Williams,6.666667,4.333333,2.5,76.041,74.512,74.336,22.817939,41.192212,...,16,90.523252,5.032703,15,6.288971,84.0,42.0,144.0,11.831093,11
11,LIN,Racing Bulls,12.000000,6.000000,3.0,76.389,74.748,74.918,22.990568,42.183667,...,15,91.297416,5.806868,20,6.724053,315.0,105.0,255.0,12.133205,12
12,COL,Alpine,7.000000,6.500000,9.0,76.189,74.758,75.179,24.279387,41.603032,...,10,91.198493,5.707945,12,5.543871,490.0,525.0,266.0,12.298518,13
13,OCO,Haas F1 Team,9.000000,4.500000,0.5,76.333,74.845,74.278,23.188343,39.963529,...,14,89.143743,3.653195,11,4.613516,323.0,19.0,187.0,12.506346,14
14,ALB,Williams,10.333333,5.666667,2.5,75.989,74.600,74.801,22.480769,40.787447,...,9,88.550772,3.060224,8,4.330093,77.0,7.0,176.0,12.908889,15
15,HUL,Audi,10.333333,5.166667,0.0,75.343,74.094,74.050,22.800765,39.044059,...,7,86.852290,1.361742,3,1.754338,26.0,0.0,130.0,13.184544,16
16,BEA,Haas F1 Team,7.333333,3.666667,0.5,76.292,74.456,74.487,24.486622,41.533528,...,5,90.913907,5.423359,5,3.585090,361.0,342.0,266.0,13.477925,17
17,BOR,Audi,8.333333,4.166667,0.0,75.750,74.359,73.820,23.170286,40.086714,...,20,90.899000,5.408452,17,6.449516,32.0,4.0,112.0,13.851956,18
18,PER,Cadillac,11.000000,5.500000,0.0,76.170,75.116,74.945,23.264833,40.141767,...,8,88.564671,3.074123,7,4.218121,0.0,0.0,324.0,16.423883,19
19,BOT,Cadillac,11.333333,5.666667,0.0,77.460,75.759,75.451,23.337667,40.748185,...,2,86.730012,1.239463,2,1.119871,0.0,0.0,400.0,16.627655,20
20,STR,Aston Martin,10.666667,5.333333,0.0,77.556,76.174,75.921,23.562741,40.432074,...,1,86.583975,1.093426,4,2.050431,0.0,0.0,484.0,16.816089,21
21,ALO,Aston Martin,11.666667,5.833333,0.0,76.678,75.294,75.567,22.958833,40.708207,...,13,89.604640,4.114092,10,4.500591,0.0,0.0,441.0,16.826443,22

In [7]:
PRE.set_index("Driver", inplace=True)
result.set_index("Driver", inplace=True)

Final = result.copy()
Final["Predicted_Pos"] = PRE["Predicted_Pos"]

PRE.reset_index(inplace=True)
Final.reset_index(inplace=True)
result.reset_index(inplace=True)

Final

   Driver  Position  Predicted_Pos
0     ANT       1.0              1
1     HAM       2.0              3
2     HAD       3.0              8
3     PIA       4.0              6
4     LAW       5.0             10
5     LIN       6.0             12
6     GAS       7.0              9
7     ALB       8.0             15
8     OCO       9.0             14
9     ALO      10.0             22
10    BOR      11.0             18
11    RUS      12.0              4
12    HUL      13.0             16
13    COL      14.0             13
14    PER      15.0             19
15    SAI      16.0             11
16    LEC      17.0              2
17    STR      18.0             21
18    NOR      19.0              7
19    BEA      20.0             17
20    BOT      21.0             20
21    VER      22.0              5

In [8]:

rho, p_value = spearmanr(Final['Position'],Final['Predicted_Pos'])

In [9]:
print(f"{rho}, {p_value}")

0.34839073969508755, 0.11206951041950931